// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaCairoLocation  sync.Once
	cacheAfricaCairoLocation *time.Location
)

type AfricaCairo struct{}

func (AfricaCairo) Location() *time.Location {
	onceAfricaCairoLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Cairo")
		if err != nil {
			panic(err)
		}
		cacheAfricaCairoLocation = loc
	})
	return cacheAfricaCairoLocation
}
