// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaHarareLocation  sync.Once
	cacheAfricaHarareLocation *time.Location
)

type AfricaHarare struct{}

func (AfricaHarare) Location() *time.Location {
	onceAfricaHarareLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Harare")
		if err != nil {
			panic(err)
		}
		cacheAfricaHarareLocation = loc
	})
	return cacheAfricaHarareLocation
}
