// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaOuagadougouLocation  sync.Once
	cacheAfricaOuagadougouLocation *time.Location
)

type AfricaOuagadougou struct{}

func (AfricaOuagadougou) Location() *time.Location {
	onceAfricaOuagadougouLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Ouagadougou")
		if err != nil {
			panic(err)
		}
		cacheAfricaOuagadougouLocation = loc
	})
	return cacheAfricaOuagadougouLocation
}
