// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaNdjamenaLocation  sync.Once
	cacheAfricaNdjamenaLocation *time.Location
)

type AfricaNdjamena struct{}

func (AfricaNdjamena) Location() *time.Location {
	onceAfricaNdjamenaLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Ndjamena")
		if err != nil {
			panic(err)
		}
		cacheAfricaNdjamenaLocation = loc
	})
	return cacheAfricaNdjamenaLocation
}
