// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaLubumbashiLocation  sync.Once
	cacheAfricaLubumbashiLocation *time.Location
)

type AfricaLubumbashi struct{}

func (AfricaLubumbashi) Location() *time.Location {
	onceAfricaLubumbashiLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Lubumbashi")
		if err != nil {
			panic(err)
		}
		cacheAfricaLubumbashiLocation = loc
	})
	return cacheAfricaLubumbashiLocation
}
