// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaBamakoLocation  sync.Once
	cacheAfricaBamakoLocation *time.Location
)

type AfricaBamako struct{}

func (AfricaBamako) Location() *time.Location {
	onceAfricaBamakoLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Bamako")
		if err != nil {
			panic(err)
		}
		cacheAfricaBamakoLocation = loc
	})
	return cacheAfricaBamakoLocation
}
