// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaKhartoumLocation  sync.Once
	cacheAfricaKhartoumLocation *time.Location
)

type AfricaKhartoum struct{}

func (AfricaKhartoum) Location() *time.Location {
	onceAfricaKhartoumLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Khartoum")
		if err != nil {
			panic(err)
		}
		cacheAfricaKhartoumLocation = loc
	})
	return cacheAfricaKhartoumLocation
}
