// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaMaseruLocation  sync.Once
	cacheAfricaMaseruLocation *time.Location
)

type AfricaMaseru struct{}

func (AfricaMaseru) Location() *time.Location {
	onceAfricaMaseruLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Maseru")
		if err != nil {
			panic(err)
		}
		cacheAfricaMaseruLocation = loc
	})
	return cacheAfricaMaseruLocation
}
