// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaNiameyLocation  sync.Once
	cacheAfricaNiameyLocation *time.Location
)

type AfricaNiamey struct{}

func (AfricaNiamey) Location() *time.Location {
	onceAfricaNiameyLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Niamey")
		if err != nil {
			panic(err)
		}
		cacheAfricaNiameyLocation = loc
	})
	return cacheAfricaNiameyLocation
}
