// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaWindhoekLocation  sync.Once
	cacheAfricaWindhoekLocation *time.Location
)

type AfricaWindhoek struct{}

func (AfricaWindhoek) Location() *time.Location {
	onceAfricaWindhoekLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Windhoek")
		if err != nil {
			panic(err)
		}
		cacheAfricaWindhoekLocation = loc
	})
	return cacheAfricaWindhoekLocation
}
