// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaTripoliLocation  sync.Once
	cacheAfricaTripoliLocation *time.Location
)

type AfricaTripoli struct{}

func (AfricaTripoli) Location() *time.Location {
	onceAfricaTripoliLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Tripoli")
		if err != nil {
			panic(err)
		}
		cacheAfricaTripoliLocation = loc
	})
	return cacheAfricaTripoliLocation
}
