// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaBrazzavilleLocation  sync.Once
	cacheAfricaBrazzavilleLocation *time.Location
)

type AfricaBrazzaville struct{}

func (AfricaBrazzaville) Location() *time.Location {
	onceAfricaBrazzavilleLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Brazzaville")
		if err != nil {
			panic(err)
		}
		cacheAfricaBrazzavilleLocation = loc
	})
	return cacheAfricaBrazzavilleLocation
}
