// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaLagosLocation  sync.Once
	cacheAfricaLagosLocation *time.Location
)

type AfricaLagos struct{}

func (AfricaLagos) Location() *time.Location {
	onceAfricaLagosLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Lagos")
		if err != nil {
			panic(err)
		}
		cacheAfricaLagosLocation = loc
	})
	return cacheAfricaLagosLocation
}
