// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaAccraLocation  sync.Once
	cacheAfricaAccraLocation *time.Location
)

type AfricaAccra struct{}

func (AfricaAccra) Location() *time.Location {
	onceAfricaAccraLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Accra")
		if err != nil {
			panic(err)
		}
		cacheAfricaAccraLocation = loc
	})
	return cacheAfricaAccraLocation
}
