// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaKinshasaLocation  sync.Once
	cacheAfricaKinshasaLocation *time.Location
)

type AfricaKinshasa struct{}

func (AfricaKinshasa) Location() *time.Location {
	onceAfricaKinshasaLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Kinshasa")
		if err != nil {
			panic(err)
		}
		cacheAfricaKinshasaLocation = loc
	})
	return cacheAfricaKinshasaLocation
}
