// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaEl_AaiunLocation  sync.Once
	cacheAfricaEl_AaiunLocation *time.Location
)

type AfricaEl_Aaiun struct{}

func (AfricaEl_Aaiun) Location() *time.Location {
	onceAfricaEl_AaiunLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/El_Aaiun")
		if err != nil {
			panic(err)
		}
		cacheAfricaEl_AaiunLocation = loc
	})
	return cacheAfricaEl_AaiunLocation
}
