// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaAbidjanLocation  sync.Once
	cacheAfricaAbidjanLocation *time.Location
)

type AfricaAbidjan struct{}

func (AfricaAbidjan) Location() *time.Location {
	onceAfricaAbidjanLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Abidjan")
		if err != nil {
			panic(err)
		}
		cacheAfricaAbidjanLocation = loc
	})
	return cacheAfricaAbidjanLocation
}
