// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaMonroviaLocation  sync.Once
	cacheAfricaMonroviaLocation *time.Location
)

type AfricaMonrovia struct{}

func (AfricaMonrovia) Location() *time.Location {
	onceAfricaMonroviaLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Monrovia")
		if err != nil {
			panic(err)
		}
		cacheAfricaMonroviaLocation = loc
	})
	return cacheAfricaMonroviaLocation
}
