// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaKigaliLocation  sync.Once
	cacheAfricaKigaliLocation *time.Location
)

type AfricaKigali struct{}

func (AfricaKigali) Location() *time.Location {
	onceAfricaKigaliLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Kigali")
		if err != nil {
			panic(err)
		}
		cacheAfricaKigaliLocation = loc
	})
	return cacheAfricaKigaliLocation
}
