// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaCeutaLocation  sync.Once
	cacheAfricaCeutaLocation *time.Location
)

type AfricaCeuta struct{}

func (AfricaCeuta) Location() *time.Location {
	onceAfricaCeutaLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Ceuta")
		if err != nil {
			panic(err)
		}
		cacheAfricaCeutaLocation = loc
	})
	return cacheAfricaCeutaLocation
}
