// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaDakarLocation  sync.Once
	cacheAfricaDakarLocation *time.Location
)

type AfricaDakar struct{}

func (AfricaDakar) Location() *time.Location {
	onceAfricaDakarLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Dakar")
		if err != nil {
			panic(err)
		}
		cacheAfricaDakarLocation = loc
	})
	return cacheAfricaDakarLocation
}
