// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaBanguiLocation  sync.Once
	cacheAfricaBanguiLocation *time.Location
)

type AfricaBangui struct{}

func (AfricaBangui) Location() *time.Location {
	onceAfricaBanguiLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Bangui")
		if err != nil {
			panic(err)
		}
		cacheAfricaBanguiLocation = loc
	})
	return cacheAfricaBanguiLocation
}
