// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaBanjulLocation  sync.Once
	cacheAfricaBanjulLocation *time.Location
)

type AfricaBanjul struct{}

func (AfricaBanjul) Location() *time.Location {
	onceAfricaBanjulLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Banjul")
		if err != nil {
			panic(err)
		}
		cacheAfricaBanjulLocation = loc
	})
	return cacheAfricaBanjulLocation
}
