// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaNouakchottLocation  sync.Once
	cacheAfricaNouakchottLocation *time.Location
)

type AfricaNouakchott struct{}

func (AfricaNouakchott) Location() *time.Location {
	onceAfricaNouakchottLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Nouakchott")
		if err != nil {
			panic(err)
		}
		cacheAfricaNouakchottLocation = loc
	})
	return cacheAfricaNouakchottLocation
}
