// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaAddis_AbabaLocation  sync.Once
	cacheAfricaAddis_AbabaLocation *time.Location
)

type AfricaAddis_Ababa struct{}

func (AfricaAddis_Ababa) Location() *time.Location {
	onceAfricaAddis_AbabaLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Addis_Ababa")
		if err != nil {
			panic(err)
		}
		cacheAfricaAddis_AbabaLocation = loc
	})
	return cacheAfricaAddis_AbabaLocation
}
