// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaMaputoLocation  sync.Once
	cacheAfricaMaputoLocation *time.Location
)

type AfricaMaputo struct{}

func (AfricaMaputo) Location() *time.Location {
	onceAfricaMaputoLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Maputo")
		if err != nil {
			panic(err)
		}
		cacheAfricaMaputoLocation = loc
	})
	return cacheAfricaMaputoLocation
}
