// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaPortoNovoLocation  sync.Once
	cacheAfricaPortoNovoLocation *time.Location
)

type AfricaPortoNovo struct{}

func (AfricaPortoNovo) Location() *time.Location {
	onceAfricaPortoNovoLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Porto-Novo")
		if err != nil {
			panic(err)
		}
		cacheAfricaPortoNovoLocation = loc
	})
	return cacheAfricaPortoNovoLocation
}
