// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaTunisLocation  sync.Once
	cacheAfricaTunisLocation *time.Location
)

type AfricaTunis struct{}

func (AfricaTunis) Location() *time.Location {
	onceAfricaTunisLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Tunis")
		if err != nil {
			panic(err)
		}
		cacheAfricaTunisLocation = loc
	})
	return cacheAfricaTunisLocation
}
