// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAfricaMogadishuLocation  sync.Once
	cacheAfricaMogadishuLocation *time.Location
)

type AfricaMogadishu struct{}

func (AfricaMogadishu) Location() *time.Location {
	onceAfricaMogadishuLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Mogadishu")
		if err != nil {
			panic(err)
		}
		cacheAfricaMogadishuLocation = loc
	})
	return cacheAfricaMogadishuLocation
}
