// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAfricaKampalaLocation  sync.Once
	cacheAfricaKampalaLocation *time.Location
)

type AfricaKampala struct{}

func (AfricaKampala) Location() *time.Location {
	onceAfricaKampalaLocation.Do(func() {
		loc, err := time.LoadLocation("Africa/Kampala")
		if err != nil {
			panic(err)
		}
		cacheAfricaKampalaLocation = loc
	})
	return cacheAfricaKampalaLocation
}
