// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaWinnipegLocation  sync.Once
	cacheAmericaWinnipegLocation *time.Location
)

type AmericaWinnipeg struct{}

func (AmericaWinnipeg) Location() *time.Location {
	onceAmericaWinnipegLocation.Do(func() {
		loc, err := time.LoadLocation("America/Winnipeg")
		if err != nil {
			panic(err)
		}
		cacheAmericaWinnipegLocation = loc
	})
	return cacheAmericaWinnipegLocation
}
