// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaAtikokanLocation  sync.Once
	cacheAmericaAtikokanLocation *time.Location
)

type AmericaAtikokan struct{}

func (AmericaAtikokan) Location() *time.Location {
	onceAmericaAtikokanLocation.Do(func() {
		loc, err := time.LoadLocation("America/Atikokan")
		if err != nil {
			panic(err)
		}
		cacheAmericaAtikokanLocation = loc
	})
	return cacheAmericaAtikokanLocation
}
