// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaBoiseLocation  sync.Once
	cacheAmericaBoiseLocation *time.Location
)

type AmericaBoise struct{}

func (AmericaBoise) Location() *time.Location {
	onceAmericaBoiseLocation.Do(func() {
		loc, err := time.LoadLocation("America/Boise")
		if err != nil {
			panic(err)
		}
		cacheAmericaBoiseLocation = loc
	})
	return cacheAmericaBoiseLocation
}
