// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaMendozaLocation  sync.Once
	cacheAmericaArgentinaMendozaLocation *time.Location
)

type AmericaArgentinaMendoza struct{}

func (AmericaArgentinaMendoza) Location() *time.Location {
	onceAmericaArgentinaMendozaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Mendoza")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaMendozaLocation = loc
	})
	return cacheAmericaArgentinaMendozaLocation
}
