// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaGuatemalaLocation  sync.Once
	cacheAmericaGuatemalaLocation *time.Location
)

type AmericaGuatemala struct{}

func (AmericaGuatemala) Location() *time.Location {
	onceAmericaGuatemalaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Guatemala")
		if err != nil {
			panic(err)
		}
		cacheAmericaGuatemalaLocation = loc
	})
	return cacheAmericaGuatemalaLocation
}
