// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaMonterreyLocation  sync.Once
	cacheAmericaMonterreyLocation *time.Location
)

type AmericaMonterrey struct{}

func (AmericaMonterrey) Location() *time.Location {
	onceAmericaMonterreyLocation.Do(func() {
		loc, err := time.LoadLocation("America/Monterrey")
		if err != nil {
			panic(err)
		}
		cacheAmericaMonterreyLocation = loc
	})
	return cacheAmericaMonterreyLocation
}
