// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaYakutatLocation  sync.Once
	cacheAmericaYakutatLocation *time.Location
)

type AmericaYakutat struct{}

func (AmericaYakutat) Location() *time.Location {
	onceAmericaYakutatLocation.Do(func() {
		loc, err := time.LoadLocation("America/Yakutat")
		if err != nil {
			panic(err)
		}
		cacheAmericaYakutatLocation = loc
	})
	return cacheAmericaYakutatLocation
}
