// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaPunta_ArenasLocation  sync.Once
	cacheAmericaPunta_ArenasLocation *time.Location
)

type AmericaPunta_Arenas struct{}

func (AmericaPunta_Arenas) Location() *time.Location {
	onceAmericaPunta_ArenasLocation.Do(func() {
		loc, err := time.LoadLocation("America/Punta_Arenas")
		if err != nil {
			panic(err)
		}
		cacheAmericaPunta_ArenasLocation = loc
	})
	return cacheAmericaPunta_ArenasLocation
}
