// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaSt_ThomasLocation  sync.Once
	cacheAmericaSt_ThomasLocation *time.Location
)

type AmericaSt_Thomas struct{}

func (AmericaSt_Thomas) Location() *time.Location {
	onceAmericaSt_ThomasLocation.Do(func() {
		loc, err := time.LoadLocation("America/St_Thomas")
		if err != nil {
			panic(err)
		}
		cacheAmericaSt_ThomasLocation = loc
	})
	return cacheAmericaSt_ThomasLocation
}
