// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaIndianaVincennesLocation  sync.Once
	cacheAmericaIndianaVincennesLocation *time.Location
)

type AmericaIndianaVincennes struct{}

func (AmericaIndianaVincennes) Location() *time.Location {
	onceAmericaIndianaVincennesLocation.Do(func() {
		loc, err := time.LoadLocation("America/Indiana/Vincennes")
		if err != nil {
			panic(err)
		}
		cacheAmericaIndianaVincennesLocation = loc
	})
	return cacheAmericaIndianaVincennesLocation
}
