// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaKentuckyMonticelloLocation  sync.Once
	cacheAmericaKentuckyMonticelloLocation *time.Location
)

type AmericaKentuckyMonticello struct{}

func (AmericaKentuckyMonticello) Location() *time.Location {
	onceAmericaKentuckyMonticelloLocation.Do(func() {
		loc, err := time.LoadLocation("America/Kentucky/Monticello")
		if err != nil {
			panic(err)
		}
		cacheAmericaKentuckyMonticelloLocation = loc
	})
	return cacheAmericaKentuckyMonticelloLocation
}
