// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaMartiniqueLocation  sync.Once
	cacheAmericaMartiniqueLocation *time.Location
)

type AmericaMartinique struct{}

func (AmericaMartinique) Location() *time.Location {
	onceAmericaMartiniqueLocation.Do(func() {
		loc, err := time.LoadLocation("America/Martinique")
		if err != nil {
			panic(err)
		}
		cacheAmericaMartiniqueLocation = loc
	})
	return cacheAmericaMartiniqueLocation
}
