// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaIndianaWinamacLocation  sync.Once
	cacheAmericaIndianaWinamacLocation *time.Location
)

type AmericaIndianaWinamac struct{}

func (AmericaIndianaWinamac) Location() *time.Location {
	onceAmericaIndianaWinamacLocation.Do(func() {
		loc, err := time.LoadLocation("America/Indiana/Winamac")
		if err != nil {
			panic(err)
		}
		cacheAmericaIndianaWinamacLocation = loc
	})
	return cacheAmericaIndianaWinamacLocation
}
