// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaNorth_DakotaNew_SalemLocation  sync.Once
	cacheAmericaNorth_DakotaNew_SalemLocation *time.Location
)

type AmericaNorth_DakotaNew_Salem struct{}

func (AmericaNorth_DakotaNew_Salem) Location() *time.Location {
	onceAmericaNorth_DakotaNew_SalemLocation.Do(func() {
		loc, err := time.LoadLocation("America/North_Dakota/New_Salem")
		if err != nil {
			panic(err)
		}
		cacheAmericaNorth_DakotaNew_SalemLocation = loc
	})
	return cacheAmericaNorth_DakotaNew_SalemLocation
}
