// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaTegucigalpaLocation  sync.Once
	cacheAmericaTegucigalpaLocation *time.Location
)

type AmericaTegucigalpa struct{}

func (AmericaTegucigalpa) Location() *time.Location {
	onceAmericaTegucigalpaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Tegucigalpa")
		if err != nil {
			panic(err)
		}
		cacheAmericaTegucigalpaLocation = loc
	})
	return cacheAmericaTegucigalpaLocation
}
