// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaLower_PrincesLocation  sync.Once
	cacheAmericaLower_PrincesLocation *time.Location
)

type AmericaLower_Princes struct{}

func (AmericaLower_Princes) Location() *time.Location {
	onceAmericaLower_PrincesLocation.Do(func() {
		loc, err := time.LoadLocation("America/Lower_Princes")
		if err != nil {
			panic(err)
		}
		cacheAmericaLower_PrincesLocation = loc
	})
	return cacheAmericaLower_PrincesLocation
}
