// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaBahiaLocation  sync.Once
	cacheAmericaBahiaLocation *time.Location
)

type AmericaBahia struct{}

func (AmericaBahia) Location() *time.Location {
	onceAmericaBahiaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Bahia")
		if err != nil {
			panic(err)
		}
		cacheAmericaBahiaLocation = loc
	})
	return cacheAmericaBahiaLocation
}
