// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaUshuaiaLocation  sync.Once
	cacheAmericaArgentinaUshuaiaLocation *time.Location
)

type AmericaArgentinaUshuaia struct{}

func (AmericaArgentinaUshuaia) Location() *time.Location {
	onceAmericaArgentinaUshuaiaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Ushuaia")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaUshuaiaLocation = loc
	})
	return cacheAmericaArgentinaUshuaiaLocation
}
