// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaAntiguaLocation  sync.Once
	cacheAmericaAntiguaLocation *time.Location
)

type AmericaAntigua struct{}

func (AmericaAntigua) Location() *time.Location {
	onceAmericaAntiguaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Antigua")
		if err != nil {
			panic(err)
		}
		cacheAmericaAntiguaLocation = loc
	})
	return cacheAmericaAntiguaLocation
}
