// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaManausLocation  sync.Once
	cacheAmericaManausLocation *time.Location
)

type AmericaManaus struct{}

func (AmericaManaus) Location() *time.Location {
	onceAmericaManausLocation.Do(func() {
		loc, err := time.LoadLocation("America/Manaus")
		if err != nil {
			panic(err)
		}
		cacheAmericaManausLocation = loc
	})
	return cacheAmericaManausLocation
}
