// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaOjinagaLocation  sync.Once
	cacheAmericaOjinagaLocation *time.Location
)

type AmericaOjinaga struct{}

func (AmericaOjinaga) Location() *time.Location {
	onceAmericaOjinagaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Ojinaga")
		if err != nil {
			panic(err)
		}
		cacheAmericaOjinagaLocation = loc
	})
	return cacheAmericaOjinagaLocation
}
