// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaBlancSablonLocation  sync.Once
	cacheAmericaBlancSablonLocation *time.Location
)

type AmericaBlancSablon struct{}

func (AmericaBlancSablon) Location() *time.Location {
	onceAmericaBlancSablonLocation.Do(func() {
		loc, err := time.LoadLocation("America/Blanc-Sablon")
		if err != nil {
			panic(err)
		}
		cacheAmericaBlancSablonLocation = loc
	})
	return cacheAmericaBlancSablonLocation
}
