// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaCrestonLocation  sync.Once
	cacheAmericaCrestonLocation *time.Location
)

type AmericaCreston struct{}

func (AmericaCreston) Location() *time.Location {
	onceAmericaCrestonLocation.Do(func() {
		loc, err := time.LoadLocation("America/Creston")
		if err != nil {
			panic(err)
		}
		cacheAmericaCrestonLocation = loc
	})
	return cacheAmericaCrestonLocation
}
