// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaNassauLocation  sync.Once
	cacheAmericaNassauLocation *time.Location
)

type AmericaNassau struct{}

func (AmericaNassau) Location() *time.Location {
	onceAmericaNassauLocation.Do(func() {
		loc, err := time.LoadLocation("America/Nassau")
		if err != nil {
			panic(err)
		}
		cacheAmericaNassauLocation = loc
	})
	return cacheAmericaNassauLocation
}
