// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaDominicaLocation  sync.Once
	cacheAmericaDominicaLocation *time.Location
)

type AmericaDominica struct{}

func (AmericaDominica) Location() *time.Location {
	onceAmericaDominicaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Dominica")
		if err != nil {
			panic(err)
		}
		cacheAmericaDominicaLocation = loc
	})
	return cacheAmericaDominicaLocation
}
