// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaPortauPrinceLocation  sync.Once
	cacheAmericaPortauPrinceLocation *time.Location
)

type AmericaPortauPrince struct{}

func (AmericaPortauPrince) Location() *time.Location {
	onceAmericaPortauPrinceLocation.Do(func() {
		loc, err := time.LoadLocation("America/Port-au-Prince")
		if err != nil {
			panic(err)
		}
		cacheAmericaPortauPrinceLocation = loc
	})
	return cacheAmericaPortauPrinceLocation
}
