// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaSt_BarthelemyLocation  sync.Once
	cacheAmericaSt_BarthelemyLocation *time.Location
)

type AmericaSt_Barthelemy struct{}

func (AmericaSt_Barthelemy) Location() *time.Location {
	onceAmericaSt_BarthelemyLocation.Do(func() {
		loc, err := time.LoadLocation("America/St_Barthelemy")
		if err != nil {
			panic(err)
		}
		cacheAmericaSt_BarthelemyLocation = loc
	})
	return cacheAmericaSt_BarthelemyLocation
}
