// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaLa_PazLocation  sync.Once
	cacheAmericaLa_PazLocation *time.Location
)

type AmericaLa_Paz struct{}

func (AmericaLa_Paz) Location() *time.Location {
	onceAmericaLa_PazLocation.Do(func() {
		loc, err := time.LoadLocation("America/La_Paz")
		if err != nil {
			panic(err)
		}
		cacheAmericaLa_PazLocation = loc
	})
	return cacheAmericaLa_PazLocation
}
