// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaGlace_BayLocation  sync.Once
	cacheAmericaGlace_BayLocation *time.Location
)

type AmericaGlace_Bay struct{}

func (AmericaGlace_Bay) Location() *time.Location {
	onceAmericaGlace_BayLocation.Do(func() {
		loc, err := time.LoadLocation("America/Glace_Bay")
		if err != nil {
			panic(err)
		}
		cacheAmericaGlace_BayLocation = loc
	})
	return cacheAmericaGlace_BayLocation
}
