// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaMiquelonLocation  sync.Once
	cacheAmericaMiquelonLocation *time.Location
)

type AmericaMiquelon struct{}

func (AmericaMiquelon) Location() *time.Location {
	onceAmericaMiquelonLocation.Do(func() {
		loc, err := time.LoadLocation("America/Miquelon")
		if err != nil {
			panic(err)
		}
		cacheAmericaMiquelonLocation = loc
	})
	return cacheAmericaMiquelonLocation
}
