// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaSao_PauloLocation  sync.Once
	cacheAmericaSao_PauloLocation *time.Location
)

type AmericaSao_Paulo struct{}

func (AmericaSao_Paulo) Location() *time.Location {
	onceAmericaSao_PauloLocation.Do(func() {
		loc, err := time.LoadLocation("America/Sao_Paulo")
		if err != nil {
			panic(err)
		}
		cacheAmericaSao_PauloLocation = loc
	})
	return cacheAmericaSao_PauloLocation
}
