// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaDanmarkshavnLocation  sync.Once
	cacheAmericaDanmarkshavnLocation *time.Location
)

type AmericaDanmarkshavn struct{}

func (AmericaDanmarkshavn) Location() *time.Location {
	onceAmericaDanmarkshavnLocation.Do(func() {
		loc, err := time.LoadLocation("America/Danmarkshavn")
		if err != nil {
			panic(err)
		}
		cacheAmericaDanmarkshavnLocation = loc
	})
	return cacheAmericaDanmarkshavnLocation
}
