// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaDenverLocation  sync.Once
	cacheAmericaDenverLocation *time.Location
)

type AmericaDenver struct{}

func (AmericaDenver) Location() *time.Location {
	onceAmericaDenverLocation.Do(func() {
		loc, err := time.LoadLocation("America/Denver")
		if err != nil {
			panic(err)
		}
		cacheAmericaDenverLocation = loc
	})
	return cacheAmericaDenverLocation
}
