// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaCordobaLocation  sync.Once
	cacheAmericaArgentinaCordobaLocation *time.Location
)

type AmericaArgentinaCordoba struct{}

func (AmericaArgentinaCordoba) Location() *time.Location {
	onceAmericaArgentinaCordobaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Cordoba")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaCordobaLocation = loc
	})
	return cacheAmericaArgentinaCordobaLocation
}
