// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaScoresbysundLocation  sync.Once
	cacheAmericaScoresbysundLocation *time.Location
)

type AmericaScoresbysund struct{}

func (AmericaScoresbysund) Location() *time.Location {
	onceAmericaScoresbysundLocation.Do(func() {
		loc, err := time.LoadLocation("America/Scoresbysund")
		if err != nil {
			panic(err)
		}
		cacheAmericaScoresbysundLocation = loc
	})
	return cacheAmericaScoresbysundLocation
}
