// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaCiudad_JuarezLocation  sync.Once
	cacheAmericaCiudad_JuarezLocation *time.Location
)

type AmericaCiudad_Juarez struct{}

func (AmericaCiudad_Juarez) Location() *time.Location {
	onceAmericaCiudad_JuarezLocation.Do(func() {
		loc, err := time.LoadLocation("America/Ciudad_Juarez")
		if err != nil {
			panic(err)
		}
		cacheAmericaCiudad_JuarezLocation = loc
	})
	return cacheAmericaCiudad_JuarezLocation
}
