// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaInuvikLocation  sync.Once
	cacheAmericaInuvikLocation *time.Location
)

type AmericaInuvik struct{}

func (AmericaInuvik) Location() *time.Location {
	onceAmericaInuvikLocation.Do(func() {
		loc, err := time.LoadLocation("America/Inuvik")
		if err != nil {
			panic(err)
		}
		cacheAmericaInuvikLocation = loc
	})
	return cacheAmericaInuvikLocation
}
