// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaCuracaoLocation  sync.Once
	cacheAmericaCuracaoLocation *time.Location
)

type AmericaCuracao struct{}

func (AmericaCuracao) Location() *time.Location {
	onceAmericaCuracaoLocation.Do(func() {
		loc, err := time.LoadLocation("America/Curacao")
		if err != nil {
			panic(err)
		}
		cacheAmericaCuracaoLocation = loc
	})
	return cacheAmericaCuracaoLocation
}
