// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaCatamarcaLocation  sync.Once
	cacheAmericaArgentinaCatamarcaLocation *time.Location
)

type AmericaArgentinaCatamarca struct{}

func (AmericaArgentinaCatamarca) Location() *time.Location {
	onceAmericaArgentinaCatamarcaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Catamarca")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaCatamarcaLocation = loc
	})
	return cacheAmericaArgentinaCatamarcaLocation
}
