// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaMetlakatlaLocation  sync.Once
	cacheAmericaMetlakatlaLocation *time.Location
)

type AmericaMetlakatla struct{}

func (AmericaMetlakatla) Location() *time.Location {
	onceAmericaMetlakatlaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Metlakatla")
		if err != nil {
			panic(err)
		}
		cacheAmericaMetlakatlaLocation = loc
	})
	return cacheAmericaMetlakatlaLocation
}
