// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaTorontoLocation  sync.Once
	cacheAmericaTorontoLocation *time.Location
)

type AmericaToronto struct{}

func (AmericaToronto) Location() *time.Location {
	onceAmericaTorontoLocation.Do(func() {
		loc, err := time.LoadLocation("America/Toronto")
		if err != nil {
			panic(err)
		}
		cacheAmericaTorontoLocation = loc
	})
	return cacheAmericaTorontoLocation
}
