// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaHavanaLocation  sync.Once
	cacheAmericaHavanaLocation *time.Location
)

type AmericaHavana struct{}

func (AmericaHavana) Location() *time.Location {
	onceAmericaHavanaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Havana")
		if err != nil {
			panic(err)
		}
		cacheAmericaHavanaLocation = loc
	})
	return cacheAmericaHavanaLocation
}
