// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaTortolaLocation  sync.Once
	cacheAmericaTortolaLocation *time.Location
)

type AmericaTortola struct{}

func (AmericaTortola) Location() *time.Location {
	onceAmericaTortolaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Tortola")
		if err != nil {
			panic(err)
		}
		cacheAmericaTortolaLocation = loc
	})
	return cacheAmericaTortolaLocation
}
