// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaMexico_CityLocation  sync.Once
	cacheAmericaMexico_CityLocation *time.Location
)

type AmericaMexico_City struct{}

func (AmericaMexico_City) Location() *time.Location {
	onceAmericaMexico_CityLocation.Do(func() {
		loc, err := time.LoadLocation("America/Mexico_City")
		if err != nil {
			panic(err)
		}
		cacheAmericaMexico_CityLocation = loc
	})
	return cacheAmericaMexico_CityLocation
}
