// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaFort_NelsonLocation  sync.Once
	cacheAmericaFort_NelsonLocation *time.Location
)

type AmericaFort_Nelson struct{}

func (AmericaFort_Nelson) Location() *time.Location {
	onceAmericaFort_NelsonLocation.Do(func() {
		loc, err := time.LoadLocation("America/Fort_Nelson")
		if err != nil {
			panic(err)
		}
		cacheAmericaFort_NelsonLocation = loc
	})
	return cacheAmericaFort_NelsonLocation
}
