// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaBuenos_AiresLocation  sync.Once
	cacheAmericaArgentinaBuenos_AiresLocation *time.Location
)

type AmericaArgentinaBuenos_Aires struct{}

func (AmericaArgentinaBuenos_Aires) Location() *time.Location {
	onceAmericaArgentinaBuenos_AiresLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Buenos_Aires")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaBuenos_AiresLocation = loc
	})
	return cacheAmericaArgentinaBuenos_AiresLocation
}
