// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaEl_SalvadorLocation  sync.Once
	cacheAmericaEl_SalvadorLocation *time.Location
)

type AmericaEl_Salvador struct{}

func (AmericaEl_Salvador) Location() *time.Location {
	onceAmericaEl_SalvadorLocation.Do(func() {
		loc, err := time.LoadLocation("America/El_Salvador")
		if err != nil {
			panic(err)
		}
		cacheAmericaEl_SalvadorLocation = loc
	})
	return cacheAmericaEl_SalvadorLocation
}
