// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaWhitehorseLocation  sync.Once
	cacheAmericaWhitehorseLocation *time.Location
)

type AmericaWhitehorse struct{}

func (AmericaWhitehorse) Location() *time.Location {
	onceAmericaWhitehorseLocation.Do(func() {
		loc, err := time.LoadLocation("America/Whitehorse")
		if err != nil {
			panic(err)
		}
		cacheAmericaWhitehorseLocation = loc
	})
	return cacheAmericaWhitehorseLocation
}
