// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaGoose_BayLocation  sync.Once
	cacheAmericaGoose_BayLocation *time.Location
)

type AmericaGoose_Bay struct{}

func (AmericaGoose_Bay) Location() *time.Location {
	onceAmericaGoose_BayLocation.Do(func() {
		loc, err := time.LoadLocation("America/Goose_Bay")
		if err != nil {
			panic(err)
		}
		cacheAmericaGoose_BayLocation = loc
	})
	return cacheAmericaGoose_BayLocation
}
