// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaCancunLocation  sync.Once
	cacheAmericaCancunLocation *time.Location
)

type AmericaCancun struct{}

func (AmericaCancun) Location() *time.Location {
	onceAmericaCancunLocation.Do(func() {
		loc, err := time.LoadLocation("America/Cancun")
		if err != nil {
			panic(err)
		}
		cacheAmericaCancunLocation = loc
	})
	return cacheAmericaCancunLocation
}
