// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaBelizeLocation  sync.Once
	cacheAmericaBelizeLocation *time.Location
)

type AmericaBelize struct{}

func (AmericaBelize) Location() *time.Location {
	onceAmericaBelizeLocation.Do(func() {
		loc, err := time.LoadLocation("America/Belize")
		if err != nil {
			panic(err)
		}
		cacheAmericaBelizeLocation = loc
	})
	return cacheAmericaBelizeLocation
}
