// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaNorth_DakotaCenterLocation  sync.Once
	cacheAmericaNorth_DakotaCenterLocation *time.Location
)

type AmericaNorth_DakotaCenter struct{}

func (AmericaNorth_DakotaCenter) Location() *time.Location {
	onceAmericaNorth_DakotaCenterLocation.Do(func() {
		loc, err := time.LoadLocation("America/North_Dakota/Center")
		if err != nil {
			panic(err)
		}
		cacheAmericaNorth_DakotaCenterLocation = loc
	})
	return cacheAmericaNorth_DakotaCenterLocation
}
