// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaReginaLocation  sync.Once
	cacheAmericaReginaLocation *time.Location
)

type AmericaRegina struct{}

func (AmericaRegina) Location() *time.Location {
	onceAmericaReginaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Regina")
		if err != nil {
			panic(err)
		}
		cacheAmericaReginaLocation = loc
	})
	return cacheAmericaReginaLocation
}
