// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaBarbadosLocation  sync.Once
	cacheAmericaBarbadosLocation *time.Location
)

type AmericaBarbados struct{}

func (AmericaBarbados) Location() *time.Location {
	onceAmericaBarbadosLocation.Do(func() {
		loc, err := time.LoadLocation("America/Barbados")
		if err != nil {
			panic(err)
		}
		cacheAmericaBarbadosLocation = loc
	})
	return cacheAmericaBarbadosLocation
}
