// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaSan_JuanLocation  sync.Once
	cacheAmericaArgentinaSan_JuanLocation *time.Location
)

type AmericaArgentinaSan_Juan struct{}

func (AmericaArgentinaSan_Juan) Location() *time.Location {
	onceAmericaArgentinaSan_JuanLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/San_Juan")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaSan_JuanLocation = loc
	})
	return cacheAmericaArgentinaSan_JuanLocation
}
