// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaRecifeLocation  sync.Once
	cacheAmericaRecifeLocation *time.Location
)

type AmericaRecife struct{}

func (AmericaRecife) Location() *time.Location {
	onceAmericaRecifeLocation.Do(func() {
		loc, err := time.LoadLocation("America/Recife")
		if err != nil {
			panic(err)
		}
		cacheAmericaRecifeLocation = loc
	})
	return cacheAmericaRecifeLocation
}
