// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaJuneauLocation  sync.Once
	cacheAmericaJuneauLocation *time.Location
)

type AmericaJuneau struct{}

func (AmericaJuneau) Location() *time.Location {
	onceAmericaJuneauLocation.Do(func() {
		loc, err := time.LoadLocation("America/Juneau")
		if err != nil {
			panic(err)
		}
		cacheAmericaJuneauLocation = loc
	})
	return cacheAmericaJuneauLocation
}
