// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaNomeLocation  sync.Once
	cacheAmericaNomeLocation *time.Location
)

type AmericaNome struct{}

func (AmericaNome) Location() *time.Location {
	onceAmericaNomeLocation.Do(func() {
		loc, err := time.LoadLocation("America/Nome")
		if err != nil {
			panic(err)
		}
		cacheAmericaNomeLocation = loc
	})
	return cacheAmericaNomeLocation
}
