// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaCaracasLocation  sync.Once
	cacheAmericaCaracasLocation *time.Location
)

type AmericaCaracas struct{}

func (AmericaCaracas) Location() *time.Location {
	onceAmericaCaracasLocation.Do(func() {
		loc, err := time.LoadLocation("America/Caracas")
		if err != nil {
			panic(err)
		}
		cacheAmericaCaracasLocation = loc
	})
	return cacheAmericaCaracasLocation
}
