// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaSwift_CurrentLocation  sync.Once
	cacheAmericaSwift_CurrentLocation *time.Location
)

type AmericaSwift_Current struct{}

func (AmericaSwift_Current) Location() *time.Location {
	onceAmericaSwift_CurrentLocation.Do(func() {
		loc, err := time.LoadLocation("America/Swift_Current")
		if err != nil {
			panic(err)
		}
		cacheAmericaSwift_CurrentLocation = loc
	})
	return cacheAmericaSwift_CurrentLocation
}
