// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaMeridaLocation  sync.Once
	cacheAmericaMeridaLocation *time.Location
)

type AmericaMerida struct{}

func (AmericaMerida) Location() *time.Location {
	onceAmericaMeridaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Merida")
		if err != nil {
			panic(err)
		}
		cacheAmericaMeridaLocation = loc
	})
	return cacheAmericaMeridaLocation
}
