// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaKralendijkLocation  sync.Once
	cacheAmericaKralendijkLocation *time.Location
)

type AmericaKralendijk struct{}

func (AmericaKralendijk) Location() *time.Location {
	onceAmericaKralendijkLocation.Do(func() {
		loc, err := time.LoadLocation("America/Kralendijk")
		if err != nil {
			panic(err)
		}
		cacheAmericaKralendijkLocation = loc
	})
	return cacheAmericaKralendijkLocation
}
