// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaGuyanaLocation  sync.Once
	cacheAmericaGuyanaLocation *time.Location
)

type AmericaGuyana struct{}

func (AmericaGuyana) Location() *time.Location {
	onceAmericaGuyanaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Guyana")
		if err != nil {
			panic(err)
		}
		cacheAmericaGuyanaLocation = loc
	})
	return cacheAmericaGuyanaLocation
}
