// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaSt_VincentLocation  sync.Once
	cacheAmericaSt_VincentLocation *time.Location
)

type AmericaSt_Vincent struct{}

func (AmericaSt_Vincent) Location() *time.Location {
	onceAmericaSt_VincentLocation.Do(func() {
		loc, err := time.LoadLocation("America/St_Vincent")
		if err != nil {
			panic(err)
		}
		cacheAmericaSt_VincentLocation = loc
	})
	return cacheAmericaSt_VincentLocation
}
