// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaRio_GallegosLocation  sync.Once
	cacheAmericaArgentinaRio_GallegosLocation *time.Location
)

type AmericaArgentinaRio_Gallegos struct{}

func (AmericaArgentinaRio_Gallegos) Location() *time.Location {
	onceAmericaArgentinaRio_GallegosLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Rio_Gallegos")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaRio_GallegosLocation = loc
	})
	return cacheAmericaArgentinaRio_GallegosLocation
}
