// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaEirunepeLocation  sync.Once
	cacheAmericaEirunepeLocation *time.Location
)

type AmericaEirunepe struct{}

func (AmericaEirunepe) Location() *time.Location {
	onceAmericaEirunepeLocation.Do(func() {
		loc, err := time.LoadLocation("America/Eirunepe")
		if err != nil {
			panic(err)
		}
		cacheAmericaEirunepeLocation = loc
	})
	return cacheAmericaEirunepeLocation
}
