// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaKentuckyLouisvilleLocation  sync.Once
	cacheAmericaKentuckyLouisvilleLocation *time.Location
)

type AmericaKentuckyLouisville struct{}

func (AmericaKentuckyLouisville) Location() *time.Location {
	onceAmericaKentuckyLouisvilleLocation.Do(func() {
		loc, err := time.LoadLocation("America/Kentucky/Louisville")
		if err != nil {
			panic(err)
		}
		cacheAmericaKentuckyLouisvilleLocation = loc
	})
	return cacheAmericaKentuckyLouisvilleLocation
}
