// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaCosta_RicaLocation  sync.Once
	cacheAmericaCosta_RicaLocation *time.Location
)

type AmericaCosta_Rica struct{}

func (AmericaCosta_Rica) Location() *time.Location {
	onceAmericaCosta_RicaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Costa_Rica")
		if err != nil {
			panic(err)
		}
		cacheAmericaCosta_RicaLocation = loc
	})
	return cacheAmericaCosta_RicaLocation
}
