// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaMonctonLocation  sync.Once
	cacheAmericaMonctonLocation *time.Location
)

type AmericaMoncton struct{}

func (AmericaMoncton) Location() *time.Location {
	onceAmericaMonctonLocation.Do(func() {
		loc, err := time.LoadLocation("America/Moncton")
		if err != nil {
			panic(err)
		}
		cacheAmericaMonctonLocation = loc
	})
	return cacheAmericaMonctonLocation
}
