// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaNoronhaLocation  sync.Once
	cacheAmericaNoronhaLocation *time.Location
)

type AmericaNoronha struct{}

func (AmericaNoronha) Location() *time.Location {
	onceAmericaNoronhaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Noronha")
		if err != nil {
			panic(err)
		}
		cacheAmericaNoronhaLocation = loc
	})
	return cacheAmericaNoronhaLocation
}
