// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaResoluteLocation  sync.Once
	cacheAmericaResoluteLocation *time.Location
)

type AmericaResolute struct{}

func (AmericaResolute) Location() *time.Location {
	onceAmericaResoluteLocation.Do(func() {
		loc, err := time.LoadLocation("America/Resolute")
		if err != nil {
			panic(err)
		}
		cacheAmericaResoluteLocation = loc
	})
	return cacheAmericaResoluteLocation
}
