// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaDetroitLocation  sync.Once
	cacheAmericaDetroitLocation *time.Location
)

type AmericaDetroit struct{}

func (AmericaDetroit) Location() *time.Location {
	onceAmericaDetroitLocation.Do(func() {
		loc, err := time.LoadLocation("America/Detroit")
		if err != nil {
			panic(err)
		}
		cacheAmericaDetroitLocation = loc
	})
	return cacheAmericaDetroitLocation
}
