// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaVancouverLocation  sync.Once
	cacheAmericaVancouverLocation *time.Location
)

type AmericaVancouver struct{}

func (AmericaVancouver) Location() *time.Location {
	onceAmericaVancouverLocation.Do(func() {
		loc, err := time.LoadLocation("America/Vancouver")
		if err != nil {
			panic(err)
		}
		cacheAmericaVancouverLocation = loc
	})
	return cacheAmericaVancouverLocation
}
