// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaIndianaKnoxLocation  sync.Once
	cacheAmericaIndianaKnoxLocation *time.Location
)

type AmericaIndianaKnox struct{}

func (AmericaIndianaKnox) Location() *time.Location {
	onceAmericaIndianaKnoxLocation.Do(func() {
		loc, err := time.LoadLocation("America/Indiana/Knox")
		if err != nil {
			panic(err)
		}
		cacheAmericaIndianaKnoxLocation = loc
	})
	return cacheAmericaIndianaKnoxLocation
}
