// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaIqaluitLocation  sync.Once
	cacheAmericaIqaluitLocation *time.Location
)

type AmericaIqaluit struct{}

func (AmericaIqaluit) Location() *time.Location {
	onceAmericaIqaluitLocation.Do(func() {
		loc, err := time.LoadLocation("America/Iqaluit")
		if err != nil {
			panic(err)
		}
		cacheAmericaIqaluitLocation = loc
	})
	return cacheAmericaIqaluitLocation
}
