// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaNorth_DakotaBeulahLocation  sync.Once
	cacheAmericaNorth_DakotaBeulahLocation *time.Location
)

type AmericaNorth_DakotaBeulah struct{}

func (AmericaNorth_DakotaBeulah) Location() *time.Location {
	onceAmericaNorth_DakotaBeulahLocation.Do(func() {
		loc, err := time.LoadLocation("America/North_Dakota/Beulah")
		if err != nil {
			panic(err)
		}
		cacheAmericaNorth_DakotaBeulahLocation = loc
	})
	return cacheAmericaNorth_DakotaBeulahLocation
}
