// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaPort_of_SpainLocation  sync.Once
	cacheAmericaPort_of_SpainLocation *time.Location
)

type AmericaPort_of_Spain struct{}

func (AmericaPort_of_Spain) Location() *time.Location {
	onceAmericaPort_of_SpainLocation.Do(func() {
		loc, err := time.LoadLocation("America/Port_of_Spain")
		if err != nil {
			panic(err)
		}
		cacheAmericaPort_of_SpainLocation = loc
	})
	return cacheAmericaPort_of_SpainLocation
}
