// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaChicagoLocation  sync.Once
	cacheAmericaChicagoLocation *time.Location
)

type AmericaChicago struct{}

func (AmericaChicago) Location() *time.Location {
	onceAmericaChicagoLocation.Do(func() {
		loc, err := time.LoadLocation("America/Chicago")
		if err != nil {
			panic(err)
		}
		cacheAmericaChicagoLocation = loc
	})
	return cacheAmericaChicagoLocation
}
