// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaIndianaIndianapolisLocation  sync.Once
	cacheAmericaIndianaIndianapolisLocation *time.Location
)

type AmericaIndianaIndianapolis struct{}

func (AmericaIndianaIndianapolis) Location() *time.Location {
	onceAmericaIndianaIndianapolisLocation.Do(func() {
		loc, err := time.LoadLocation("America/Indiana/Indianapolis")
		if err != nil {
			panic(err)
		}
		cacheAmericaIndianaIndianapolisLocation = loc
	})
	return cacheAmericaIndianaIndianapolisLocation
}
