// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaSaltaLocation  sync.Once
	cacheAmericaArgentinaSaltaLocation *time.Location
)

type AmericaArgentinaSalta struct{}

func (AmericaArgentinaSalta) Location() *time.Location {
	onceAmericaArgentinaSaltaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Salta")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaSaltaLocation = loc
	})
	return cacheAmericaArgentinaSaltaLocation
}
