// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaIndianaVevayLocation  sync.Once
	cacheAmericaIndianaVevayLocation *time.Location
)

type AmericaIndianaVevay struct{}

func (AmericaIndianaVevay) Location() *time.Location {
	onceAmericaIndianaVevayLocation.Do(func() {
		loc, err := time.LoadLocation("America/Indiana/Vevay")
		if err != nil {
			panic(err)
		}
		cacheAmericaIndianaVevayLocation = loc
	})
	return cacheAmericaIndianaVevayLocation
}
