// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaManaguaLocation  sync.Once
	cacheAmericaManaguaLocation *time.Location
)

type AmericaManagua struct{}

func (AmericaManagua) Location() *time.Location {
	onceAmericaManaguaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Managua")
		if err != nil {
			panic(err)
		}
		cacheAmericaManaguaLocation = loc
	})
	return cacheAmericaManaguaLocation
}
