// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaMaceioLocation  sync.Once
	cacheAmericaMaceioLocation *time.Location
)

type AmericaMaceio struct{}

func (AmericaMaceio) Location() *time.Location {
	onceAmericaMaceioLocation.Do(func() {
		loc, err := time.LoadLocation("America/Maceio")
		if err != nil {
			panic(err)
		}
		cacheAmericaMaceioLocation = loc
	})
	return cacheAmericaMaceioLocation
}
