// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaGuadeloupeLocation  sync.Once
	cacheAmericaGuadeloupeLocation *time.Location
)

type AmericaGuadeloupe struct{}

func (AmericaGuadeloupe) Location() *time.Location {
	onceAmericaGuadeloupeLocation.Do(func() {
		loc, err := time.LoadLocation("America/Guadeloupe")
		if err != nil {
			panic(err)
		}
		cacheAmericaGuadeloupeLocation = loc
	})
	return cacheAmericaGuadeloupeLocation
}
