// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaJujuyLocation  sync.Once
	cacheAmericaArgentinaJujuyLocation *time.Location
)

type AmericaArgentinaJujuy struct{}

func (AmericaArgentinaJujuy) Location() *time.Location {
	onceAmericaArgentinaJujuyLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/Jujuy")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaJujuyLocation = loc
	})
	return cacheAmericaArgentinaJujuyLocation
}
