// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaIndianaMarengoLocation  sync.Once
	cacheAmericaIndianaMarengoLocation *time.Location
)

type AmericaIndianaMarengo struct{}

func (AmericaIndianaMarengo) Location() *time.Location {
	onceAmericaIndianaMarengoLocation.Do(func() {
		loc, err := time.LoadLocation("America/Indiana/Marengo")
		if err != nil {
			panic(err)
		}
		cacheAmericaIndianaMarengoLocation = loc
	})
	return cacheAmericaIndianaMarengoLocation
}
