// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaNew_YorkLocation  sync.Once
	cacheAmericaNew_YorkLocation *time.Location
)

type AmericaNew_York struct{}

func (AmericaNew_York) Location() *time.Location {
	onceAmericaNew_YorkLocation.Do(func() {
		loc, err := time.LoadLocation("America/New_York")
		if err != nil {
			panic(err)
		}
		cacheAmericaNew_YorkLocation = loc
	})
	return cacheAmericaNew_YorkLocation
}
