// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaBahia_BanderasLocation  sync.Once
	cacheAmericaBahia_BanderasLocation *time.Location
)

type AmericaBahia_Banderas struct{}

func (AmericaBahia_Banderas) Location() *time.Location {
	onceAmericaBahia_BanderasLocation.Do(func() {
		loc, err := time.LoadLocation("America/Bahia_Banderas")
		if err != nil {
			panic(err)
		}
		cacheAmericaBahia_BanderasLocation = loc
	})
	return cacheAmericaBahia_BanderasLocation
}
