// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaSitkaLocation  sync.Once
	cacheAmericaSitkaLocation *time.Location
)

type AmericaSitka struct{}

func (AmericaSitka) Location() *time.Location {
	onceAmericaSitkaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Sitka")
		if err != nil {
			panic(err)
		}
		cacheAmericaSitkaLocation = loc
	})
	return cacheAmericaSitkaLocation
}
