// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaArgentinaSan_LuisLocation  sync.Once
	cacheAmericaArgentinaSan_LuisLocation *time.Location
)

type AmericaArgentinaSan_Luis struct{}

func (AmericaArgentinaSan_Luis) Location() *time.Location {
	onceAmericaArgentinaSan_LuisLocation.Do(func() {
		loc, err := time.LoadLocation("America/Argentina/San_Luis")
		if err != nil {
			panic(err)
		}
		cacheAmericaArgentinaSan_LuisLocation = loc
	})
	return cacheAmericaArgentinaSan_LuisLocation
}
