// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAmericaAraguainaLocation  sync.Once
	cacheAmericaAraguainaLocation *time.Location
)

type AmericaAraguaina struct{}

func (AmericaAraguaina) Location() *time.Location {
	onceAmericaAraguainaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Araguaina")
		if err != nil {
			panic(err)
		}
		cacheAmericaAraguainaLocation = loc
	})
	return cacheAmericaAraguainaLocation
}
