// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAmericaTijuanaLocation  sync.Once
	cacheAmericaTijuanaLocation *time.Location
)

type AmericaTijuana struct{}

func (AmericaTijuana) Location() *time.Location {
	onceAmericaTijuanaLocation.Do(func() {
		loc, err := time.LoadLocation("America/Tijuana")
		if err != nil {
			panic(err)
		}
		cacheAmericaTijuanaLocation = loc
	})
	return cacheAmericaTijuanaLocation
}
