// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAntarcticaRotheraLocation  sync.Once
	cacheAntarcticaRotheraLocation *time.Location
)

type AntarcticaRothera struct{}

func (AntarcticaRothera) Location() *time.Location {
	onceAntarcticaRotheraLocation.Do(func() {
		loc, err := time.LoadLocation("Antarctica/Rothera")
		if err != nil {
			panic(err)
		}
		cacheAntarcticaRotheraLocation = loc
	})
	return cacheAntarcticaRotheraLocation
}
