// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAntarcticaMawsonLocation  sync.Once
	cacheAntarcticaMawsonLocation *time.Location
)

type AntarcticaMawson struct{}

func (AntarcticaMawson) Location() *time.Location {
	onceAntarcticaMawsonLocation.Do(func() {
		loc, err := time.LoadLocation("Antarctica/Mawson")
		if err != nil {
			panic(err)
		}
		cacheAntarcticaMawsonLocation = loc
	})
	return cacheAntarcticaMawsonLocation
}
