// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAntarcticaDumontDUrvilleLocation  sync.Once
	cacheAntarcticaDumontDUrvilleLocation *time.Location
)

type AntarcticaDumontDUrville struct{}

func (AntarcticaDumontDUrville) Location() *time.Location {
	onceAntarcticaDumontDUrvilleLocation.Do(func() {
		loc, err := time.LoadLocation("Antarctica/DumontDUrville")
		if err != nil {
			panic(err)
		}
		cacheAntarcticaDumontDUrvilleLocation = loc
	})
	return cacheAntarcticaDumontDUrvilleLocation
}
