// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAntarcticaVostokLocation  sync.Once
	cacheAntarcticaVostokLocation *time.Location
)

type AntarcticaVostok struct{}

func (AntarcticaVostok) Location() *time.Location {
	onceAntarcticaVostokLocation.Do(func() {
		loc, err := time.LoadLocation("Antarctica/Vostok")
		if err != nil {
			panic(err)
		}
		cacheAntarcticaVostokLocation = loc
	})
	return cacheAntarcticaVostokLocation
}
