// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAntarcticaSyowaLocation  sync.Once
	cacheAntarcticaSyowaLocation *time.Location
)

type AntarcticaSyowa struct{}

func (AntarcticaSyowa) Location() *time.Location {
	onceAntarcticaSyowaLocation.Do(func() {
		loc, err := time.LoadLocation("Antarctica/Syowa")
		if err != nil {
			panic(err)
		}
		cacheAntarcticaSyowaLocation = loc
	})
	return cacheAntarcticaSyowaLocation
}
