// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAntarcticaCaseyLocation  sync.Once
	cacheAntarcticaCaseyLocation *time.Location
)

type AntarcticaCasey struct{}

func (AntarcticaCasey) Location() *time.Location {
	onceAntarcticaCaseyLocation.Do(func() {
		loc, err := time.LoadLocation("Antarctica/Casey")
		if err != nil {
			panic(err)
		}
		cacheAntarcticaCaseyLocation = loc
	})
	return cacheAntarcticaCaseyLocation
}
