// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceArcticLongyearbyenLocation  sync.Once
	cacheArcticLongyearbyenLocation *time.Location
)

type ArcticLongyearbyen struct{}

func (ArcticLongyearbyen) Location() *time.Location {
	onceArcticLongyearbyenLocation.Do(func() {
		loc, err := time.LoadLocation("Arctic/Longyearbyen")
		if err != nil {
			panic(err)
		}
		cacheArcticLongyearbyenLocation = loc
	})
	return cacheArcticLongyearbyenLocation
}
