// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaTomskLocation  sync.Once
	cacheAsiaTomskLocation *time.Location
)

type AsiaTomsk struct{}

func (AsiaTomsk) Location() *time.Location {
	onceAsiaTomskLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Tomsk")
		if err != nil {
			panic(err)
		}
		cacheAsiaTomskLocation = loc
	})
	return cacheAsiaTomskLocation
}
