// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaGazaLocation  sync.Once
	cacheAsiaGazaLocation *time.Location
)

type AsiaGaza struct{}

func (AsiaGaza) Location() *time.Location {
	onceAsiaGazaLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Gaza")
		if err != nil {
			panic(err)
		}
		cacheAsiaGazaLocation = loc
	})
	return cacheAsiaGazaLocation
}
