// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaThimphuLocation  sync.Once
	cacheAsiaThimphuLocation *time.Location
)

type AsiaThimphu struct{}

func (AsiaThimphu) Location() *time.Location {
	onceAsiaThimphuLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Thimphu")
		if err != nil {
			panic(err)
		}
		cacheAsiaThimphuLocation = loc
	})
	return cacheAsiaThimphuLocation
}
