// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaJayapuraLocation  sync.Once
	cacheAsiaJayapuraLocation *time.Location
)

type AsiaJayapura struct{}

func (AsiaJayapura) Location() *time.Location {
	onceAsiaJayapuraLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Jayapura")
		if err != nil {
			panic(err)
		}
		cacheAsiaJayapuraLocation = loc
	})
	return cacheAsiaJayapuraLocation
}
