// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaKolkataLocation  sync.Once
	cacheAsiaKolkataLocation *time.Location
)

type AsiaKolkata struct{}

func (AsiaKolkata) Location() *time.Location {
	onceAsiaKolkataLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Kolkata")
		if err != nil {
			panic(err)
		}
		cacheAsiaKolkataLocation = loc
	})
	return cacheAsiaKolkataLocation
}
