// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaNovosibirskLocation  sync.Once
	cacheAsiaNovosibirskLocation *time.Location
)

type AsiaNovosibirsk struct{}

func (AsiaNovosibirsk) Location() *time.Location {
	onceAsiaNovosibirskLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Novosibirsk")
		if err != nil {
			panic(err)
		}
		cacheAsiaNovosibirskLocation = loc
	})
	return cacheAsiaNovosibirskLocation
}
