// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaSrednekolymskLocation  sync.Once
	cacheAsiaSrednekolymskLocation *time.Location
)

type AsiaSrednekolymsk struct{}

func (AsiaSrednekolymsk) Location() *time.Location {
	onceAsiaSrednekolymskLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Srednekolymsk")
		if err != nil {
			panic(err)
		}
		cacheAsiaSrednekolymskLocation = loc
	})
	return cacheAsiaSrednekolymskLocation
}
