// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaHong_KongLocation  sync.Once
	cacheAsiaHong_KongLocation *time.Location
)

type AsiaHong_Kong struct{}

func (AsiaHong_Kong) Location() *time.Location {
	onceAsiaHong_KongLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Hong_Kong")
		if err != nil {
			panic(err)
		}
		cacheAsiaHong_KongLocation = loc
	})
	return cacheAsiaHong_KongLocation
}
