// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaBishkekLocation  sync.Once
	cacheAsiaBishkekLocation *time.Location
)

type AsiaBishkek struct{}

func (AsiaBishkek) Location() *time.Location {
	onceAsiaBishkekLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Bishkek")
		if err != nil {
			panic(err)
		}
		cacheAsiaBishkekLocation = loc
	})
	return cacheAsiaBishkekLocation
}
