// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaKhandygaLocation  sync.Once
	cacheAsiaKhandygaLocation *time.Location
)

type AsiaKhandyga struct{}

func (AsiaKhandyga) Location() *time.Location {
	onceAsiaKhandygaLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Khandyga")
		if err != nil {
			panic(err)
		}
		cacheAsiaKhandygaLocation = loc
	})
	return cacheAsiaKhandygaLocation
}
