// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaHebronLocation  sync.Once
	cacheAsiaHebronLocation *time.Location
)

type AsiaHebron struct{}

func (AsiaHebron) Location() *time.Location {
	onceAsiaHebronLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Hebron")
		if err != nil {
			panic(err)
		}
		cacheAsiaHebronLocation = loc
	})
	return cacheAsiaHebronLocation
}
