// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaBangkokLocation  sync.Once
	cacheAsiaBangkokLocation *time.Location
)

type AsiaBangkok struct{}

func (AsiaBangkok) Location() *time.Location {
	onceAsiaBangkokLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Bangkok")
		if err != nil {
			panic(err)
		}
		cacheAsiaBangkokLocation = loc
	})
	return cacheAsiaBangkokLocation
}
