// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaTokyoLocation  sync.Once
	cacheAsiaTokyoLocation *time.Location
)

type AsiaTokyo struct{}

func (AsiaTokyo) Location() *time.Location {
	onceAsiaTokyoLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Tokyo")
		if err != nil {
			panic(err)
		}
		cacheAsiaTokyoLocation = loc
	})
	return cacheAsiaTokyoLocation
}
