// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaSeoulLocation  sync.Once
	cacheAsiaSeoulLocation *time.Location
)

type AsiaSeoul struct{}

func (AsiaSeoul) Location() *time.Location {
	onceAsiaSeoulLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Seoul")
		if err != nil {
			panic(err)
		}
		cacheAsiaSeoulLocation = loc
	})
	return cacheAsiaSeoulLocation
}
