// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaAmmanLocation  sync.Once
	cacheAsiaAmmanLocation *time.Location
)

type AsiaAmman struct{}

func (AsiaAmman) Location() *time.Location {
	onceAsiaAmmanLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Amman")
		if err != nil {
			panic(err)
		}
		cacheAsiaAmmanLocation = loc
	})
	return cacheAsiaAmmanLocation
}
