// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaHo_Chi_MinhLocation  sync.Once
	cacheAsiaHo_Chi_MinhLocation *time.Location
)

type AsiaHo_Chi_Minh struct{}

func (AsiaHo_Chi_Minh) Location() *time.Location {
	onceAsiaHo_Chi_MinhLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Ho_Chi_Minh")
		if err != nil {
			panic(err)
		}
		cacheAsiaHo_Chi_MinhLocation = loc
	})
	return cacheAsiaHo_Chi_MinhLocation
}
