// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaDubaiLocation  sync.Once
	cacheAsiaDubaiLocation *time.Location
)

type AsiaDubai struct{}

func (AsiaDubai) Location() *time.Location {
	onceAsiaDubaiLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Dubai")
		if err != nil {
			panic(err)
		}
		cacheAsiaDubaiLocation = loc
	})
	return cacheAsiaDubaiLocation
}
