// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaTehranLocation  sync.Once
	cacheAsiaTehranLocation *time.Location
)

type AsiaTehran struct{}

func (AsiaTehran) Location() *time.Location {
	onceAsiaTehranLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Tehran")
		if err != nil {
			panic(err)
		}
		cacheAsiaTehranLocation = loc
	})
	return cacheAsiaTehranLocation
}
