// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaDamascusLocation  sync.Once
	cacheAsiaDamascusLocation *time.Location
)

type AsiaDamascus struct{}

func (AsiaDamascus) Location() *time.Location {
	onceAsiaDamascusLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Damascus")
		if err != nil {
			panic(err)
		}
		cacheAsiaDamascusLocation = loc
	})
	return cacheAsiaDamascusLocation
}
