// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaSingaporeLocation  sync.Once
	cacheAsiaSingaporeLocation *time.Location
)

type AsiaSingapore struct{}

func (AsiaSingapore) Location() *time.Location {
	onceAsiaSingaporeLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Singapore")
		if err != nil {
			panic(err)
		}
		cacheAsiaSingaporeLocation = loc
	})
	return cacheAsiaSingaporeLocation
}
