// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaMakassarLocation  sync.Once
	cacheAsiaMakassarLocation *time.Location
)

type AsiaMakassar struct{}

func (AsiaMakassar) Location() *time.Location {
	onceAsiaMakassarLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Makassar")
		if err != nil {
			panic(err)
		}
		cacheAsiaMakassarLocation = loc
	})
	return cacheAsiaMakassarLocation
}
