// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaBakuLocation  sync.Once
	cacheAsiaBakuLocation *time.Location
)

type AsiaBaku struct{}

func (AsiaBaku) Location() *time.Location {
	onceAsiaBakuLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Baku")
		if err != nil {
			panic(err)
		}
		cacheAsiaBakuLocation = loc
	})
	return cacheAsiaBakuLocation
}
