// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaPhnom_PenhLocation  sync.Once
	cacheAsiaPhnom_PenhLocation *time.Location
)

type AsiaPhnom_Penh struct{}

func (AsiaPhnom_Penh) Location() *time.Location {
	onceAsiaPhnom_PenhLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Phnom_Penh")
		if err != nil {
			panic(err)
		}
		cacheAsiaPhnom_PenhLocation = loc
	})
	return cacheAsiaPhnom_PenhLocation
}
