// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaUrumqiLocation  sync.Once
	cacheAsiaUrumqiLocation *time.Location
)

type AsiaUrumqi struct{}

func (AsiaUrumqi) Location() *time.Location {
	onceAsiaUrumqiLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Urumqi")
		if err != nil {
			panic(err)
		}
		cacheAsiaUrumqiLocation = loc
	})
	return cacheAsiaUrumqiLocation
}
