// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaMagadanLocation  sync.Once
	cacheAsiaMagadanLocation *time.Location
)

type AsiaMagadan struct{}

func (AsiaMagadan) Location() *time.Location {
	onceAsiaMagadanLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Magadan")
		if err != nil {
			panic(err)
		}
		cacheAsiaMagadanLocation = loc
	})
	return cacheAsiaMagadanLocation
}
