// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaBaghdadLocation  sync.Once
	cacheAsiaBaghdadLocation *time.Location
)

type AsiaBaghdad struct{}

func (AsiaBaghdad) Location() *time.Location {
	onceAsiaBaghdadLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Baghdad")
		if err != nil {
			panic(err)
		}
		cacheAsiaBaghdadLocation = loc
	})
	return cacheAsiaBaghdadLocation
}
