// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaOralLocation  sync.Once
	cacheAsiaOralLocation *time.Location
)

type AsiaOral struct{}

func (AsiaOral) Location() *time.Location {
	onceAsiaOralLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Oral")
		if err != nil {
			panic(err)
		}
		cacheAsiaOralLocation = loc
	})
	return cacheAsiaOralLocation
}
