// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaChoibalsanLocation  sync.Once
	cacheAsiaChoibalsanLocation *time.Location
)

type AsiaChoibalsan struct{}

func (AsiaChoibalsan) Location() *time.Location {
	onceAsiaChoibalsanLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Choibalsan")
		if err != nil {
			panic(err)
		}
		cacheAsiaChoibalsanLocation = loc
	})
	return cacheAsiaChoibalsanLocation
}
