// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaNovokuznetskLocation  sync.Once
	cacheAsiaNovokuznetskLocation *time.Location
)

type AsiaNovokuznetsk struct{}

func (AsiaNovokuznetsk) Location() *time.Location {
	onceAsiaNovokuznetskLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Novokuznetsk")
		if err != nil {
			panic(err)
		}
		cacheAsiaNovokuznetskLocation = loc
	})
	return cacheAsiaNovokuznetskLocation
}
