// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaKarachiLocation  sync.Once
	cacheAsiaKarachiLocation *time.Location
)

type AsiaKarachi struct{}

func (AsiaKarachi) Location() *time.Location {
	onceAsiaKarachiLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Karachi")
		if err != nil {
			panic(err)
		}
		cacheAsiaKarachiLocation = loc
	})
	return cacheAsiaKarachiLocation
}
