// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaKrasnoyarskLocation  sync.Once
	cacheAsiaKrasnoyarskLocation *time.Location
)

type AsiaKrasnoyarsk struct{}

func (AsiaKrasnoyarsk) Location() *time.Location {
	onceAsiaKrasnoyarskLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Krasnoyarsk")
		if err != nil {
			panic(err)
		}
		cacheAsiaKrasnoyarskLocation = loc
	})
	return cacheAsiaKrasnoyarskLocation
}
