// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaSamarkandLocation  sync.Once
	cacheAsiaSamarkandLocation *time.Location
)

type AsiaSamarkand struct{}

func (AsiaSamarkand) Location() *time.Location {
	onceAsiaSamarkandLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Samarkand")
		if err != nil {
			panic(err)
		}
		cacheAsiaSamarkandLocation = loc
	})
	return cacheAsiaSamarkandLocation
}
