// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaBarnaulLocation  sync.Once
	cacheAsiaBarnaulLocation *time.Location
)

type AsiaBarnaul struct{}

func (AsiaBarnaul) Location() *time.Location {
	onceAsiaBarnaulLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Barnaul")
		if err != nil {
			panic(err)
		}
		cacheAsiaBarnaulLocation = loc
	})
	return cacheAsiaBarnaulLocation
}
