// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaTbilisiLocation  sync.Once
	cacheAsiaTbilisiLocation *time.Location
)

type AsiaTbilisi struct{}

func (AsiaTbilisi) Location() *time.Location {
	onceAsiaTbilisiLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Tbilisi")
		if err != nil {
			panic(err)
		}
		cacheAsiaTbilisiLocation = loc
	})
	return cacheAsiaTbilisiLocation
}
