// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaQyzylordaLocation  sync.Once
	cacheAsiaQyzylordaLocation *time.Location
)

type AsiaQyzylorda struct{}

func (AsiaQyzylorda) Location() *time.Location {
	onceAsiaQyzylordaLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Qyzylorda")
		if err != nil {
			panic(err)
		}
		cacheAsiaQyzylordaLocation = loc
	})
	return cacheAsiaQyzylordaLocation
}
