// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaSakhalinLocation  sync.Once
	cacheAsiaSakhalinLocation *time.Location
)

type AsiaSakhalin struct{}

func (AsiaSakhalin) Location() *time.Location {
	onceAsiaSakhalinLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Sakhalin")
		if err != nil {
			panic(err)
		}
		cacheAsiaSakhalinLocation = loc
	})
	return cacheAsiaSakhalinLocation
}
