// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaChitaLocation  sync.Once
	cacheAsiaChitaLocation *time.Location
)

type AsiaChita struct{}

func (AsiaChita) Location() *time.Location {
	onceAsiaChitaLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Chita")
		if err != nil {
			panic(err)
		}
		cacheAsiaChitaLocation = loc
	})
	return cacheAsiaChitaLocation
}
