// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaVientianeLocation  sync.Once
	cacheAsiaVientianeLocation *time.Location
)

type AsiaVientiane struct{}

func (AsiaVientiane) Location() *time.Location {
	onceAsiaVientianeLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Vientiane")
		if err != nil {
			panic(err)
		}
		cacheAsiaVientianeLocation = loc
	})
	return cacheAsiaVientianeLocation
}
