// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaPontianakLocation  sync.Once
	cacheAsiaPontianakLocation *time.Location
)

type AsiaPontianak struct{}

func (AsiaPontianak) Location() *time.Location {
	onceAsiaPontianakLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Pontianak")
		if err != nil {
			panic(err)
		}
		cacheAsiaPontianakLocation = loc
	})
	return cacheAsiaPontianakLocation
}
