// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaRiyadhLocation  sync.Once
	cacheAsiaRiyadhLocation *time.Location
)

type AsiaRiyadh struct{}

func (AsiaRiyadh) Location() *time.Location {
	onceAsiaRiyadhLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Riyadh")
		if err != nil {
			panic(err)
		}
		cacheAsiaRiyadhLocation = loc
	})
	return cacheAsiaRiyadhLocation
}
