// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaPyongyangLocation  sync.Once
	cacheAsiaPyongyangLocation *time.Location
)

type AsiaPyongyang struct{}

func (AsiaPyongyang) Location() *time.Location {
	onceAsiaPyongyangLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Pyongyang")
		if err != nil {
			panic(err)
		}
		cacheAsiaPyongyangLocation = loc
	})
	return cacheAsiaPyongyangLocation
}
