// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaDushanbeLocation  sync.Once
	cacheAsiaDushanbeLocation *time.Location
)

type AsiaDushanbe struct{}

func (AsiaDushanbe) Location() *time.Location {
	onceAsiaDushanbeLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Dushanbe")
		if err != nil {
			panic(err)
		}
		cacheAsiaDushanbeLocation = loc
	})
	return cacheAsiaDushanbeLocation
}
