// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaColomboLocation  sync.Once
	cacheAsiaColomboLocation *time.Location
)

type AsiaColombo struct{}

func (AsiaColombo) Location() *time.Location {
	onceAsiaColomboLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Colombo")
		if err != nil {
			panic(err)
		}
		cacheAsiaColomboLocation = loc
	})
	return cacheAsiaColomboLocation
}
