// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaNicosiaLocation  sync.Once
	cacheAsiaNicosiaLocation *time.Location
)

type AsiaNicosia struct{}

func (AsiaNicosia) Location() *time.Location {
	onceAsiaNicosiaLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Nicosia")
		if err != nil {
			panic(err)
		}
		cacheAsiaNicosiaLocation = loc
	})
	return cacheAsiaNicosiaLocation
}
