// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaDhakaLocation  sync.Once
	cacheAsiaDhakaLocation *time.Location
)

type AsiaDhaka struct{}

func (AsiaDhaka) Location() *time.Location {
	onceAsiaDhakaLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Dhaka")
		if err != nil {
			panic(err)
		}
		cacheAsiaDhakaLocation = loc
	})
	return cacheAsiaDhakaLocation
}
