// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaAlmatyLocation  sync.Once
	cacheAsiaAlmatyLocation *time.Location
)

type AsiaAlmaty struct{}

func (AsiaAlmaty) Location() *time.Location {
	onceAsiaAlmatyLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Almaty")
		if err != nil {
			panic(err)
		}
		cacheAsiaAlmatyLocation = loc
	})
	return cacheAsiaAlmatyLocation
}
