// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaTaipeiLocation  sync.Once
	cacheAsiaTaipeiLocation *time.Location
)

type AsiaTaipei struct{}

func (AsiaTaipei) Location() *time.Location {
	onceAsiaTaipeiLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Taipei")
		if err != nil {
			panic(err)
		}
		cacheAsiaTaipeiLocation = loc
	})
	return cacheAsiaTaipeiLocation
}
