// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaDiliLocation  sync.Once
	cacheAsiaDiliLocation *time.Location
)

type AsiaDili struct{}

func (AsiaDili) Location() *time.Location {
	onceAsiaDiliLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Dili")
		if err != nil {
			panic(err)
		}
		cacheAsiaDiliLocation = loc
	})
	return cacheAsiaDiliLocation
}
