// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaQatarLocation  sync.Once
	cacheAsiaQatarLocation *time.Location
)

type AsiaQatar struct{}

func (AsiaQatar) Location() *time.Location {
	onceAsiaQatarLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Qatar")
		if err != nil {
			panic(err)
		}
		cacheAsiaQatarLocation = loc
	})
	return cacheAsiaQatarLocation
}
