// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaKuala_LumpurLocation  sync.Once
	cacheAsiaKuala_LumpurLocation *time.Location
)

type AsiaKuala_Lumpur struct{}

func (AsiaKuala_Lumpur) Location() *time.Location {
	onceAsiaKuala_LumpurLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Kuala_Lumpur")
		if err != nil {
			panic(err)
		}
		cacheAsiaKuala_LumpurLocation = loc
	})
	return cacheAsiaKuala_LumpurLocation
}
