// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAsiaMacauLocation  sync.Once
	cacheAsiaMacauLocation *time.Location
)

type AsiaMacau struct{}

func (AsiaMacau) Location() *time.Location {
	onceAsiaMacauLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Macau")
		if err != nil {
			panic(err)
		}
		cacheAsiaMacauLocation = loc
	})
	return cacheAsiaMacauLocation
}
