// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAsiaYakutskLocation  sync.Once
	cacheAsiaYakutskLocation *time.Location
)

type AsiaYakutsk struct{}

func (AsiaYakutsk) Location() *time.Location {
	onceAsiaYakutskLocation.Do(func() {
		loc, err := time.LoadLocation("Asia/Yakutsk")
		if err != nil {
			panic(err)
		}
		cacheAsiaYakutskLocation = loc
	})
	return cacheAsiaYakutskLocation
}
