// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAtlanticSt_HelenaLocation  sync.Once
	cacheAtlanticSt_HelenaLocation *time.Location
)

type AtlanticSt_Helena struct{}

func (AtlanticSt_Helena) Location() *time.Location {
	onceAtlanticSt_HelenaLocation.Do(func() {
		loc, err := time.LoadLocation("Atlantic/St_Helena")
		if err != nil {
			panic(err)
		}
		cacheAtlanticSt_HelenaLocation = loc
	})
	return cacheAtlanticSt_HelenaLocation
}
