// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAtlanticSouth_GeorgiaLocation  sync.Once
	cacheAtlanticSouth_GeorgiaLocation *time.Location
)

type AtlanticSouth_Georgia struct{}

func (AtlanticSouth_Georgia) Location() *time.Location {
	onceAtlanticSouth_GeorgiaLocation.Do(func() {
		loc, err := time.LoadLocation("Atlantic/South_Georgia")
		if err != nil {
			panic(err)
		}
		cacheAtlanticSouth_GeorgiaLocation = loc
	})
	return cacheAtlanticSouth_GeorgiaLocation
}
