// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAtlanticMadeiraLocation  sync.Once
	cacheAtlanticMadeiraLocation *time.Location
)

type AtlanticMadeira struct{}

func (AtlanticMadeira) Location() *time.Location {
	onceAtlanticMadeiraLocation.Do(func() {
		loc, err := time.LoadLocation("Atlantic/Madeira")
		if err != nil {
			panic(err)
		}
		cacheAtlanticMadeiraLocation = loc
	})
	return cacheAtlanticMadeiraLocation
}
