// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAtlanticBermudaLocation  sync.Once
	cacheAtlanticBermudaLocation *time.Location
)

type AtlanticBermuda struct{}

func (AtlanticBermuda) Location() *time.Location {
	onceAtlanticBermudaLocation.Do(func() {
		loc, err := time.LoadLocation("Atlantic/Bermuda")
		if err != nil {
			panic(err)
		}
		cacheAtlanticBermudaLocation = loc
	})
	return cacheAtlanticBermudaLocation
}
