// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAtlanticCape_VerdeLocation  sync.Once
	cacheAtlanticCape_VerdeLocation *time.Location
)

type AtlanticCape_Verde struct{}

func (AtlanticCape_Verde) Location() *time.Location {
	onceAtlanticCape_VerdeLocation.Do(func() {
		loc, err := time.LoadLocation("Atlantic/Cape_Verde")
		if err != nil {
			panic(err)
		}
		cacheAtlanticCape_VerdeLocation = loc
	})
	return cacheAtlanticCape_VerdeLocation
}
