// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAtlanticStanleyLocation  sync.Once
	cacheAtlanticStanleyLocation *time.Location
)

type AtlanticStanley struct{}

func (AtlanticStanley) Location() *time.Location {
	onceAtlanticStanleyLocation.Do(func() {
		loc, err := time.LoadLocation("Atlantic/Stanley")
		if err != nil {
			panic(err)
		}
		cacheAtlanticStanleyLocation = loc
	})
	return cacheAtlanticStanleyLocation
}
