// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAtlanticReykjavikLocation  sync.Once
	cacheAtlanticReykjavikLocation *time.Location
)

type AtlanticReykjavik struct{}

func (AtlanticReykjavik) Location() *time.Location {
	onceAtlanticReykjavikLocation.Do(func() {
		loc, err := time.LoadLocation("Atlantic/Reykjavik")
		if err != nil {
			panic(err)
		}
		cacheAtlanticReykjavikLocation = loc
	})
	return cacheAtlanticReykjavikLocation
}
