// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAustraliaMelbourneLocation  sync.Once
	cacheAustraliaMelbourneLocation *time.Location
)

type AustraliaMelbourne struct{}

func (AustraliaMelbourne) Location() *time.Location {
	onceAustraliaMelbourneLocation.Do(func() {
		loc, err := time.LoadLocation("Australia/Melbourne")
		if err != nil {
			panic(err)
		}
		cacheAustraliaMelbourneLocation = loc
	})
	return cacheAustraliaMelbourneLocation
}
