// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAustraliaDarwinLocation  sync.Once
	cacheAustraliaDarwinLocation *time.Location
)

type AustraliaDarwin struct{}

func (AustraliaDarwin) Location() *time.Location {
	onceAustraliaDarwinLocation.Do(func() {
		loc, err := time.LoadLocation("Australia/Darwin")
		if err != nil {
			panic(err)
		}
		cacheAustraliaDarwinLocation = loc
	})
	return cacheAustraliaDarwinLocation
}
