// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceAustraliaEuclaLocation  sync.Once
	cacheAustraliaEuclaLocation *time.Location
)

type AustraliaEucla struct{}

func (AustraliaEucla) Location() *time.Location {
	onceAustraliaEuclaLocation.Do(func() {
		loc, err := time.LoadLocation("Australia/Eucla")
		if err != nil {
			panic(err)
		}
		cacheAustraliaEuclaLocation = loc
	})
	return cacheAustraliaEuclaLocation
}
