// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAustraliaLord_HoweLocation  sync.Once
	cacheAustraliaLord_HoweLocation *time.Location
)

type AustraliaLord_Howe struct{}

func (AustraliaLord_Howe) Location() *time.Location {
	onceAustraliaLord_HoweLocation.Do(func() {
		loc, err := time.LoadLocation("Australia/Lord_Howe")
		if err != nil {
			panic(err)
		}
		cacheAustraliaLord_HoweLocation = loc
	})
	return cacheAustraliaLord_HoweLocation
}
