// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAustraliaSydneyLocation  sync.Once
	cacheAustraliaSydneyLocation *time.Location
)

type AustraliaSydney struct{}

func (AustraliaSydney) Location() *time.Location {
	onceAustraliaSydneyLocation.Do(func() {
		loc, err := time.LoadLocation("Australia/Sydney")
		if err != nil {
			panic(err)
		}
		cacheAustraliaSydneyLocation = loc
	})
	return cacheAustraliaSydneyLocation
}
