// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAustraliaAdelaideLocation  sync.Once
	cacheAustraliaAdelaideLocation *time.Location
)

type AustraliaAdelaide struct{}

func (AustraliaAdelaide) Location() *time.Location {
	onceAustraliaAdelaideLocation.Do(func() {
		loc, err := time.LoadLocation("Australia/Adelaide")
		if err != nil {
			panic(err)
		}
		cacheAustraliaAdelaideLocation = loc
	})
	return cacheAustraliaAdelaideLocation
}
