// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceAustraliaBrisbaneLocation  sync.Once
	cacheAustraliaBrisbaneLocation *time.Location
)

type AustraliaBrisbane struct{}

func (AustraliaBrisbane) Location() *time.Location {
	onceAustraliaBrisbaneLocation.Do(func() {
		loc, err := time.LoadLocation("Australia/Brisbane")
		if err != nil {
			panic(err)
		}
		cacheAustraliaBrisbaneLocation = loc
	})
	return cacheAustraliaBrisbaneLocation
}
