// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeSofiaLocation  sync.Once
	cacheEuropeSofiaLocation *time.Location
)

type EuropeSofia struct{}

func (EuropeSofia) Location() *time.Location {
	onceEuropeSofiaLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Sofia")
		if err != nil {
			panic(err)
		}
		cacheEuropeSofiaLocation = loc
	})
	return cacheEuropeSofiaLocation
}
