// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeLondonLocation  sync.Once
	cacheEuropeLondonLocation *time.Location
)

type EuropeLondon struct{}

func (EuropeLondon) Location() *time.Location {
	onceEuropeLondonLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/London")
		if err != nil {
			panic(err)
		}
		cacheEuropeLondonLocation = loc
	})
	return cacheEuropeLondonLocation
}
