// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeLisbonLocation  sync.Once
	cacheEuropeLisbonLocation *time.Location
)

type EuropeLisbon struct{}

func (EuropeLisbon) Location() *time.Location {
	onceEuropeLisbonLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Lisbon")
		if err != nil {
			panic(err)
		}
		cacheEuropeLisbonLocation = loc
	})
	return cacheEuropeLisbonLocation
}
