// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeVaduzLocation  sync.Once
	cacheEuropeVaduzLocation *time.Location
)

type EuropeVaduz struct{}

func (EuropeVaduz) Location() *time.Location {
	onceEuropeVaduzLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Vaduz")
		if err != nil {
			panic(err)
		}
		cacheEuropeVaduzLocation = loc
	})
	return cacheEuropeVaduzLocation
}
