// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeUlyanovskLocation  sync.Once
	cacheEuropeUlyanovskLocation *time.Location
)

type EuropeUlyanovsk struct{}

func (EuropeUlyanovsk) Location() *time.Location {
	onceEuropeUlyanovskLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Ulyanovsk")
		if err != nil {
			panic(err)
		}
		cacheEuropeUlyanovskLocation = loc
	})
	return cacheEuropeUlyanovskLocation
}
