// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeVilniusLocation  sync.Once
	cacheEuropeVilniusLocation *time.Location
)

type EuropeVilnius struct{}

func (EuropeVilnius) Location() *time.Location {
	onceEuropeVilniusLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Vilnius")
		if err != nil {
			panic(err)
		}
		cacheEuropeVilniusLocation = loc
	})
	return cacheEuropeVilniusLocation
}
