// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeLjubljanaLocation  sync.Once
	cacheEuropeLjubljanaLocation *time.Location
)

type EuropeLjubljana struct{}

func (EuropeLjubljana) Location() *time.Location {
	onceEuropeLjubljanaLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Ljubljana")
		if err != nil {
			panic(err)
		}
		cacheEuropeLjubljanaLocation = loc
	})
	return cacheEuropeLjubljanaLocation
}
