// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropePodgoricaLocation  sync.Once
	cacheEuropePodgoricaLocation *time.Location
)

type EuropePodgorica struct{}

func (EuropePodgorica) Location() *time.Location {
	onceEuropePodgoricaLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Podgorica")
		if err != nil {
			panic(err)
		}
		cacheEuropePodgoricaLocation = loc
	})
	return cacheEuropePodgoricaLocation
}
