// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeZurichLocation  sync.Once
	cacheEuropeZurichLocation *time.Location
)

type EuropeZurich struct{}

func (EuropeZurich) Location() *time.Location {
	onceEuropeZurichLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Zurich")
		if err != nil {
			panic(err)
		}
		cacheEuropeZurichLocation = loc
	})
	return cacheEuropeZurichLocation
}
