// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeAndorraLocation  sync.Once
	cacheEuropeAndorraLocation *time.Location
)

type EuropeAndorra struct{}

func (EuropeAndorra) Location() *time.Location {
	onceEuropeAndorraLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Andorra")
		if err != nil {
			panic(err)
		}
		cacheEuropeAndorraLocation = loc
	})
	return cacheEuropeAndorraLocation
}
