// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeBelgradeLocation  sync.Once
	cacheEuropeBelgradeLocation *time.Location
)

type EuropeBelgrade struct{}

func (EuropeBelgrade) Location() *time.Location {
	onceEuropeBelgradeLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Belgrade")
		if err != nil {
			panic(err)
		}
		cacheEuropeBelgradeLocation = loc
	})
	return cacheEuropeBelgradeLocation
}
