// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropePragueLocation  sync.Once
	cacheEuropePragueLocation *time.Location
)

type EuropePrague struct{}

func (EuropePrague) Location() *time.Location {
	onceEuropePragueLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Prague")
		if err != nil {
			panic(err)
		}
		cacheEuropePragueLocation = loc
	})
	return cacheEuropePragueLocation
}
