// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeAthensLocation  sync.Once
	cacheEuropeAthensLocation *time.Location
)

type EuropeAthens struct{}

func (EuropeAthens) Location() *time.Location {
	onceEuropeAthensLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Athens")
		if err != nil {
			panic(err)
		}
		cacheEuropeAthensLocation = loc
	})
	return cacheEuropeAthensLocation
}
