// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeDublinLocation  sync.Once
	cacheEuropeDublinLocation *time.Location
)

type EuropeDublin struct{}

func (EuropeDublin) Location() *time.Location {
	onceEuropeDublinLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Dublin")
		if err != nil {
			panic(err)
		}
		cacheEuropeDublinLocation = loc
	})
	return cacheEuropeDublinLocation
}
