// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeMonacoLocation  sync.Once
	cacheEuropeMonacoLocation *time.Location
)

type EuropeMonaco struct{}

func (EuropeMonaco) Location() *time.Location {
	onceEuropeMonacoLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Monaco")
		if err != nil {
			panic(err)
		}
		cacheEuropeMonacoLocation = loc
	})
	return cacheEuropeMonacoLocation
}
