// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeMoscowLocation  sync.Once
	cacheEuropeMoscowLocation *time.Location
)

type EuropeMoscow struct{}

func (EuropeMoscow) Location() *time.Location {
	onceEuropeMoscowLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Moscow")
		if err != nil {
			panic(err)
		}
		cacheEuropeMoscowLocation = loc
	})
	return cacheEuropeMoscowLocation
}
