// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeTallinnLocation  sync.Once
	cacheEuropeTallinnLocation *time.Location
)

type EuropeTallinn struct{}

func (EuropeTallinn) Location() *time.Location {
	onceEuropeTallinnLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Tallinn")
		if err != nil {
			panic(err)
		}
		cacheEuropeTallinnLocation = loc
	})
	return cacheEuropeTallinnLocation
}
