// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeStockholmLocation  sync.Once
	cacheEuropeStockholmLocation *time.Location
)

type EuropeStockholm struct{}

func (EuropeStockholm) Location() *time.Location {
	onceEuropeStockholmLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Stockholm")
		if err != nil {
			panic(err)
		}
		cacheEuropeStockholmLocation = loc
	})
	return cacheEuropeStockholmLocation
}
