// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeParisLocation  sync.Once
	cacheEuropeParisLocation *time.Location
)

type EuropeParis struct{}

func (EuropeParis) Location() *time.Location {
	onceEuropeParisLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Paris")
		if err != nil {
			panic(err)
		}
		cacheEuropeParisLocation = loc
	})
	return cacheEuropeParisLocation
}
