// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeMadridLocation  sync.Once
	cacheEuropeMadridLocation *time.Location
)

type EuropeMadrid struct{}

func (EuropeMadrid) Location() *time.Location {
	onceEuropeMadridLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Madrid")
		if err != nil {
			panic(err)
		}
		cacheEuropeMadridLocation = loc
	})
	return cacheEuropeMadridLocation
}
