// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeBudapestLocation  sync.Once
	cacheEuropeBudapestLocation *time.Location
)

type EuropeBudapest struct{}

func (EuropeBudapest) Location() *time.Location {
	onceEuropeBudapestLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Budapest")
		if err != nil {
			panic(err)
		}
		cacheEuropeBudapestLocation = loc
	})
	return cacheEuropeBudapestLocation
}
