// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeGibraltarLocation  sync.Once
	cacheEuropeGibraltarLocation *time.Location
)

type EuropeGibraltar struct{}

func (EuropeGibraltar) Location() *time.Location {
	onceEuropeGibraltarLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Gibraltar")
		if err != nil {
			panic(err)
		}
		cacheEuropeGibraltarLocation = loc
	})
	return cacheEuropeGibraltarLocation
}
