// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeRomeLocation  sync.Once
	cacheEuropeRomeLocation *time.Location
)

type EuropeRome struct{}

func (EuropeRome) Location() *time.Location {
	onceEuropeRomeLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Rome")
		if err != nil {
			panic(err)
		}
		cacheEuropeRomeLocation = loc
	})
	return cacheEuropeRomeLocation
}
