// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeKyivLocation  sync.Once
	cacheEuropeKyivLocation *time.Location
)

type EuropeKyiv struct{}

func (EuropeKyiv) Location() *time.Location {
	onceEuropeKyivLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Kyiv")
		if err != nil {
			panic(err)
		}
		cacheEuropeKyivLocation = loc
	})
	return cacheEuropeKyivLocation
}
