// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceEuropeKaliningradLocation  sync.Once
	cacheEuropeKaliningradLocation *time.Location
)

type EuropeKaliningrad struct{}

func (EuropeKaliningrad) Location() *time.Location {
	onceEuropeKaliningradLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Kaliningrad")
		if err != nil {
			panic(err)
		}
		cacheEuropeKaliningradLocation = loc
	})
	return cacheEuropeKaliningradLocation
}
