// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeAmsterdamLocation  sync.Once
	cacheEuropeAmsterdamLocation *time.Location
)

type EuropeAmsterdam struct{}

func (EuropeAmsterdam) Location() *time.Location {
	onceEuropeAmsterdamLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Amsterdam")
		if err != nil {
			panic(err)
		}
		cacheEuropeAmsterdamLocation = loc
	})
	return cacheEuropeAmsterdamLocation
}
