// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeMariehamnLocation  sync.Once
	cacheEuropeMariehamnLocation *time.Location
)

type EuropeMariehamn struct{}

func (EuropeMariehamn) Location() *time.Location {
	onceEuropeMariehamnLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Mariehamn")
		if err != nil {
			panic(err)
		}
		cacheEuropeMariehamnLocation = loc
	})
	return cacheEuropeMariehamnLocation
}
