// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeBratislavaLocation  sync.Once
	cacheEuropeBratislavaLocation *time.Location
)

type EuropeBratislava struct{}

func (EuropeBratislava) Location() *time.Location {
	onceEuropeBratislavaLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Bratislava")
		if err != nil {
			panic(err)
		}
		cacheEuropeBratislavaLocation = loc
	})
	return cacheEuropeBratislavaLocation
}
