// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeTiraneLocation  sync.Once
	cacheEuropeTiraneLocation *time.Location
)

type EuropeTirane struct{}

func (EuropeTirane) Location() *time.Location {
	onceEuropeTiraneLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Tirane")
		if err != nil {
			panic(err)
		}
		cacheEuropeTiraneLocation = loc
	})
	return cacheEuropeTiraneLocation
}
