// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceEuropeViennaLocation  sync.Once
	cacheEuropeViennaLocation *time.Location
)

type EuropeVienna struct{}

func (EuropeVienna) Location() *time.Location {
	onceEuropeViennaLocation.Do(func() {
		loc, err := time.LoadLocation("Europe/Vienna")
		if err != nil {
			panic(err)
		}
		cacheEuropeViennaLocation = loc
	})
	return cacheEuropeViennaLocation
}
