// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceIndianMaheLocation  sync.Once
	cacheIndianMaheLocation *time.Location
)

type IndianMahe struct{}

func (IndianMahe) Location() *time.Location {
	onceIndianMaheLocation.Do(func() {
		loc, err := time.LoadLocation("Indian/Mahe")
		if err != nil {
			panic(err)
		}
		cacheIndianMaheLocation = loc
	})
	return cacheIndianMaheLocation
}
