// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceIndianMauritiusLocation  sync.Once
	cacheIndianMauritiusLocation *time.Location
)

type IndianMauritius struct{}

func (IndianMauritius) Location() *time.Location {
	onceIndianMauritiusLocation.Do(func() {
		loc, err := time.LoadLocation("Indian/Mauritius")
		if err != nil {
			panic(err)
		}
		cacheIndianMauritiusLocation = loc
	})
	return cacheIndianMauritiusLocation
}
