// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceIndianReunionLocation  sync.Once
	cacheIndianReunionLocation *time.Location
)

type IndianReunion struct{}

func (IndianReunion) Location() *time.Location {
	onceIndianReunionLocation.Do(func() {
		loc, err := time.LoadLocation("Indian/Reunion")
		if err != nil {
			panic(err)
		}
		cacheIndianReunionLocation = loc
	})
	return cacheIndianReunionLocation
}
