// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceIndianCocosLocation  sync.Once
	cacheIndianCocosLocation *time.Location
)

type IndianCocos struct{}

func (IndianCocos) Location() *time.Location {
	onceIndianCocosLocation.Do(func() {
		loc, err := time.LoadLocation("Indian/Cocos")
		if err != nil {
			panic(err)
		}
		cacheIndianCocosLocation = loc
	})
	return cacheIndianCocosLocation
}
