// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	onceIndianChristmasLocation  sync.Once
	cacheIndianChristmasLocation *time.Location
)

type IndianChristmas struct{}

func (IndianChristmas) Location() *time.Location {
	onceIndianChristmasLocation.Do(func() {
		loc, err := time.LoadLocation("Indian/Christmas")
		if err != nil {
			panic(err)
		}
		cacheIndianChristmasLocation = loc
	})
	return cacheIndianChristmasLocation
}
