// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	onceIndianChagosLocation  sync.Once
	cacheIndianChagosLocation *time.Location
)

type IndianChagos struct{}

func (IndianChagos) Location() *time.Location {
	onceIndianChagosLocation.Do(func() {
		loc, err := time.LoadLocation("Indian/Chagos")
		if err != nil {
			panic(err)
		}
		cacheIndianChagosLocation = loc
	})
	return cacheIndianChagosLocation
}
