// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificNoumeaLocation  sync.Once
	cachePacificNoumeaLocation *time.Location
)

type PacificNoumea struct{}

func (PacificNoumea) Location() *time.Location {
	oncePacificNoumeaLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Noumea")
		if err != nil {
			panic(err)
		}
		cachePacificNoumeaLocation = loc
	})
	return cachePacificNoumeaLocation
}
