// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificSaipanLocation  sync.Once
	cachePacificSaipanLocation *time.Location
)

type PacificSaipan struct{}

func (PacificSaipan) Location() *time.Location {
	oncePacificSaipanLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Saipan")
		if err != nil {
			panic(err)
		}
		cachePacificSaipanLocation = loc
	})
	return cachePacificSaipanLocation
}
