// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificFunafutiLocation  sync.Once
	cachePacificFunafutiLocation *time.Location
)

type PacificFunafuti struct{}

func (PacificFunafuti) Location() *time.Location {
	oncePacificFunafutiLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Funafuti")
		if err != nil {
			panic(err)
		}
		cachePacificFunafutiLocation = loc
	})
	return cachePacificFunafutiLocation
}
