// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificMajuroLocation  sync.Once
	cachePacificMajuroLocation *time.Location
)

type PacificMajuro struct{}

func (PacificMajuro) Location() *time.Location {
	oncePacificMajuroLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Majuro")
		if err != nil {
			panic(err)
		}
		cachePacificMajuroLocation = loc
	})
	return cachePacificMajuroLocation
}
