// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificPitcairnLocation  sync.Once
	cachePacificPitcairnLocation *time.Location
)

type PacificPitcairn struct{}

func (PacificPitcairn) Location() *time.Location {
	oncePacificPitcairnLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Pitcairn")
		if err != nil {
			panic(err)
		}
		cachePacificPitcairnLocation = loc
	})
	return cachePacificPitcairnLocation
}
