// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificEfateLocation  sync.Once
	cachePacificEfateLocation *time.Location
)

type PacificEfate struct{}

func (PacificEfate) Location() *time.Location {
	oncePacificEfateLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Efate")
		if err != nil {
			panic(err)
		}
		cachePacificEfateLocation = loc
	})
	return cachePacificEfateLocation
}
