// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificChathamLocation  sync.Once
	cachePacificChathamLocation *time.Location
)

type PacificChatham struct{}

func (PacificChatham) Location() *time.Location {
	oncePacificChathamLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Chatham")
		if err != nil {
			panic(err)
		}
		cachePacificChathamLocation = loc
	})
	return cachePacificChathamLocation
}
