// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificRarotongaLocation  sync.Once
	cachePacificRarotongaLocation *time.Location
)

type PacificRarotonga struct{}

func (PacificRarotonga) Location() *time.Location {
	oncePacificRarotongaLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Rarotonga")
		if err != nil {
			panic(err)
		}
		cachePacificRarotongaLocation = loc
	})
	return cachePacificRarotongaLocation
}
