// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificTongatapuLocation  sync.Once
	cachePacificTongatapuLocation *time.Location
)

type PacificTongatapu struct{}

func (PacificTongatapu) Location() *time.Location {
	oncePacificTongatapuLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Tongatapu")
		if err != nil {
			panic(err)
		}
		cachePacificTongatapuLocation = loc
	})
	return cachePacificTongatapuLocation
}
