// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificTahitiLocation  sync.Once
	cachePacificTahitiLocation *time.Location
)

type PacificTahiti struct{}

func (PacificTahiti) Location() *time.Location {
	oncePacificTahitiLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Tahiti")
		if err != nil {
			panic(err)
		}
		cachePacificTahitiLocation = loc
	})
	return cachePacificTahitiLocation
}
