// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificKwajaleinLocation  sync.Once
	cachePacificKwajaleinLocation *time.Location
)

type PacificKwajalein struct{}

func (PacificKwajalein) Location() *time.Location {
	oncePacificKwajaleinLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Kwajalein")
		if err != nil {
			panic(err)
		}
		cachePacificKwajaleinLocation = loc
	})
	return cachePacificKwajaleinLocation
}
