// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificHonoluluLocation  sync.Once
	cachePacificHonoluluLocation *time.Location
)

type PacificHonolulu struct{}

func (PacificHonolulu) Location() *time.Location {
	oncePacificHonoluluLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Honolulu")
		if err != nil {
			panic(err)
		}
		cachePacificHonoluluLocation = loc
	})
	return cachePacificHonoluluLocation
}
