// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificPago_PagoLocation  sync.Once
	cachePacificPago_PagoLocation *time.Location
)

type PacificPago_Pago struct{}

func (PacificPago_Pago) Location() *time.Location {
	oncePacificPago_PagoLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Pago_Pago")
		if err != nil {
			panic(err)
		}
		cachePacificPago_PagoLocation = loc
	})
	return cachePacificPago_PagoLocation
}
