// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificFakaofoLocation  sync.Once
	cachePacificFakaofoLocation *time.Location
)

type PacificFakaofo struct{}

func (PacificFakaofo) Location() *time.Location {
	oncePacificFakaofoLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Fakaofo")
		if err != nil {
			panic(err)
		}
		cachePacificFakaofoLocation = loc
	})
	return cachePacificFakaofoLocation
}
