// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificEasterLocation  sync.Once
	cachePacificEasterLocation *time.Location
)

type PacificEaster struct{}

func (PacificEaster) Location() *time.Location {
	oncePacificEasterLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Easter")
		if err != nil {
			panic(err)
		}
		cachePacificEasterLocation = loc
	})
	return cachePacificEasterLocation
}
