// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificMidwayLocation  sync.Once
	cachePacificMidwayLocation *time.Location
)

type PacificMidway struct{}

func (PacificMidway) Location() *time.Location {
	oncePacificMidwayLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Midway")
		if err != nil {
			panic(err)
		}
		cachePacificMidwayLocation = loc
	})
	return cachePacificMidwayLocation
}
