// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificKantonLocation  sync.Once
	cachePacificKantonLocation *time.Location
)

type PacificKanton struct{}

func (PacificKanton) Location() *time.Location {
	oncePacificKantonLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Kanton")
		if err != nil {
			panic(err)
		}
		cachePacificKantonLocation = loc
	})
	return cachePacificKantonLocation
}
