// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificGalapagosLocation  sync.Once
	cachePacificGalapagosLocation *time.Location
)

type PacificGalapagos struct{}

func (PacificGalapagos) Location() *time.Location {
	oncePacificGalapagosLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Galapagos")
		if err != nil {
			panic(err)
		}
		cachePacificGalapagosLocation = loc
	})
	return cachePacificGalapagosLocation
}
