// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificChuukLocation  sync.Once
	cachePacificChuukLocation *time.Location
)

type PacificChuuk struct{}

func (PacificChuuk) Location() *time.Location {
	oncePacificChuukLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Chuuk")
		if err != nil {
			panic(err)
		}
		cachePacificChuukLocation = loc
	})
	return cachePacificChuukLocation
}
