// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificWallisLocation  sync.Once
	cachePacificWallisLocation *time.Location
)

type PacificWallis struct{}

func (PacificWallis) Location() *time.Location {
	oncePacificWallisLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Wallis")
		if err != nil {
			panic(err)
		}
		cachePacificWallisLocation = loc
	})
	return cachePacificWallisLocation
}
