// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificPalauLocation  sync.Once
	cachePacificPalauLocation *time.Location
)

type PacificPalau struct{}

func (PacificPalau) Location() *time.Location {
	oncePacificPalauLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Palau")
		if err != nil {
			panic(err)
		}
		cachePacificPalauLocation = loc
	})
	return cachePacificPalauLocation
}
