// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificKosraeLocation  sync.Once
	cachePacificKosraeLocation *time.Location
)

type PacificKosrae struct{}

func (PacificKosrae) Location() *time.Location {
	oncePacificKosraeLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Kosrae")
		if err != nil {
			panic(err)
		}
		cachePacificKosraeLocation = loc
	})
	return cachePacificKosraeLocation
}
