// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificPort_MoresbyLocation  sync.Once
	cachePacificPort_MoresbyLocation *time.Location
)

type PacificPort_Moresby struct{}

func (PacificPort_Moresby) Location() *time.Location {
	oncePacificPort_MoresbyLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Port_Moresby")
		if err != nil {
			panic(err)
		}
		cachePacificPort_MoresbyLocation = loc
	})
	return cachePacificPort_MoresbyLocation
}
