// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificBougainvilleLocation  sync.Once
	cachePacificBougainvilleLocation *time.Location
)

type PacificBougainville struct{}

func (PacificBougainville) Location() *time.Location {
	oncePacificBougainvilleLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Bougainville")
		if err != nil {
			panic(err)
		}
		cachePacificBougainvilleLocation = loc
	})
	return cachePacificBougainvilleLocation
}
