// Code generated by tzgen. DO NOT EDIT.
// Package model contains the types.
package tz

import "time"
import "sync"

var (
	oncePacificAucklandLocation  sync.Once
	cachePacificAucklandLocation *time.Location
)

type PacificAuckland struct{}

func (PacificAuckland) Location() *time.Location {
	oncePacificAucklandLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Auckland")
		if err != nil {
			panic(err)
		}
		cachePacificAucklandLocation = loc
	})
	return cachePacificAucklandLocation
}
