// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificWakeLocation  sync.Once
	cachePacificWakeLocation *time.Location
)

type PacificWake struct{}

func (PacificWake) Location() *time.Location {
	oncePacificWakeLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Wake")
		if err != nil {
			panic(err)
		}
		cachePacificWakeLocation = loc
	})
	return cachePacificWakeLocation
}
