// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificFijiLocation  sync.Once
	cachePacificFijiLocation *time.Location
)

type PacificFiji struct{}

func (PacificFiji) Location() *time.Location {
	oncePacificFijiLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Fiji")
		if err != nil {
			panic(err)
		}
		cachePacificFijiLocation = loc
	})
	return cachePacificFijiLocation
}
