// Code generated by tzgen. DO NOT EDIT.

package tz

import "time"
import "sync"

var (
	oncePacificNorfolkLocation  sync.Once
	cachePacificNorfolkLocation *time.Location
)

type PacificNorfolk struct{}

func (PacificNorfolk) Location() *time.Location {
	oncePacificNorfolkLocation.Do(func() {
		loc, err := time.LoadLocation("Pacific/Norfolk")
		if err != nil {
			panic(err)
		}
		cachePacificNorfolkLocation = loc
	})
	return cachePacificNorfolkLocation
}
