name: test
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        - '^1.20'
        - '^1.21'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: vet
        run: go vet ./...
      - name: Declare some variables
        id: vars
        run: |
          echo "::set-output name=coverage_txt::${RUNNER_TEMP}/coverage.txt"
      - name: Test Coverage (pkg)
        run: go test ./... -race -coverprofile=${{ steps.vars.outputs.coverage_txt }}
      - name: Upload coverage
        if: ${{ matrix.go == '^1.21' }}
        uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.vars.outputs.coverage_txt }}
